### PR TITLE
Create classes.jar if prebuilt aar does not already contain one.

### LINKED ISSUE #417: android_prebuilt_aar fails if an aar is missing a classes.jar
For example, try creating an `android_prebuilt_aar` for $ANDROID_HOME/extras/google/m2repository/com/google/android/gms/play-services/7.5.0/play-services-7.5.0.aar

### PR DESCRIPTION
**Pull request by polycoder**
resolves #417

### CODE REVIEW

**Comment by sdwilsh** [comment]
I'm going to defer to @marcinkosiba on this one actually.

**Comment by marcinkosiba** [comment]
Seems like a reasonable way to go about this. An integration test would be nice if it's not too much trouble to write one.

**Comment by polycoder** [comment]
@marcinkosiba I'll see about moving the functionality to JarDirectoryStepHelper, and will def add an integration test.

**Comment by polycoder** [comment]
@marcinkosiba I moved some of the logic to JarDirectoryStepHelper and added an integration test so this doesn't regress in the future.

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
