### PR TITLE
Add a ruletypes command that prints the list of known rule types

### PR DESCRIPTION
**Pull request by luser**
I got frustrated with the fact that the docs don't describe everything in the source, so I hacked this up so I could more easily see what rule types were available.

@sdwilsh suggests that this would be better implemented as `buck audit rules`, and also that it needs a test.

### CODE REVIEW

**Comment by luser** [comment]
`buck audit rules` already exists, so maybe `buck audit known-build-rules`.

**Comment by luser** [comment]
(The test failures in the Travis build are because I didn't update the unit tests that check the usage output.)

**Comment by sdwilsh** [comment]
You'll need to rebase your changes for us to merge this.  I commented on your change about a few minor things too.  It'd also be nice to add docs for this command (under docs/command).

@shs96c, do you have any opinions on what to call this command?  I think it's useful.

**Comment by shs96c** [comment]
buck audit rule-types

**Comment by sdwilsh** [comment]
@luser - any chance you might be up for rebasing and addressing the comment from @shs96c?

**Comment by luser** [comment]
Probably not right now, although I haven't forgotten about it. If you would like to do it yourself I won't be offended.

**Comment by nayrmi** [comment]
Closing the pull request if this is abandoned for now. We'll happily take a PR in the future, though.

Thanks!

**Pull request closed without merging**
