### PR TITLE
Enabling mvn URI for http_file and http_archive downloadables.

### PR DESCRIPTION
**Pull request by romanoid**

### CODE REVIEW

**Comment by philipjameson** [comment]
Can we please get both the unit tests and integration tests updated here?

**Comment by sdwilsh** [comment]
Why this change over using `remote_file`?

**Comment by kageiit** [comment]
> Why this change over using remote_file?

We want to use fallback url options for resolving maven artifacts as well as sha256 content hash checks and unarchive functionality for archived binaries hosted on artifactory

**Comment by romanoid** [comment]
@philipjameson thanks for suggestion, added integration tests. 

MavenUrlDecoder is already covered by unit tests. Please advice if any specific unit test you have in mind is desired.

**Comment by philipjameson** [comment]
Thanks for the updates!

**Pull request closed without merging**
