### PR TITLE
Update showcase.soy

### PR DESCRIPTION
**Pull request by darkforestzero**
adding buck built Brainium apps

### CODE REVIEW

**Comment by darkforestzero** [comment]
Thank you for your quick review.  We are happy to make the changes, but
have a few concerns:
1. It would be nice to keep all the apps together that were made by our
studio, rather than having Lyft and Uber interspersed within them.
2. Currently, all the apps listed are either owned by Facebook or are from
single app companies (Lyft, Uber).  It would be nice if there was a way to
at least show our company name, if not a link to our app webpages, since
nearly our entire catalog of apps (most of which have 1m+ downloads) are
built using buck.

Thanks,
Jonathan

**Comment by sdwilsh** [comment]
Yeah, I understand.  Do you mind if I sit on this over the weekend to figure out a way to accommodate your use case as well as more single-app places?

**Comment by darkforestzero** [comment]
Of course!  Thanks for your understanding.  Brainium is heavily invested in
Buck; it is the backbone of our multi-platform build pipeline on nearly all
our games!  We've also made a few contributions to the buck github and are
somewhat active on the google group.

Have a great weekend.

**Comment by sdwilsh** [comment]
Okay, I've thought it over and talked to some others.  I think we have a decent plan forward here, but I won't have time until tomorrow to actually implement the changes to make this work.  After that, you can rebase and adjust and continue to add apps under your section if you'd like :)

**Comment by darkforestzero** [comment]
Hi Shawn,
Wanted to check on the status of the app section change to Showcase.soy.
Thanks

**Comment by sdwilsh** [comment]
My plans for the week got a bit derailed.  We got a lot of rain recently, and water appeared in our basement, so I've had to take some time off to deal with that.  I'll get to it as soon as I can!

**Comment by darkforestzero** [comment]
Oh no!  No worries.  Good luck fixing up your place!

**Comment by sdwilsh** [comment]
@darkforestzero I've uploaded a PR that should land today that will let you rebase and be unblocked :D

**Comment by sdwilsh** [comment]
@darkforestzero ping?

**Comment by darkforestzero** [comment]
@sdwilsh I'm very confused about this whole pull request business.  I'm pretty sure I've got the soy file in a good place, and I see the work my repo (darkforestzero:patch-4), but I don't know how to get that in to master.  I don't even see another pullrequest for it.  So, I'm just going to close this and try to start from scratch

**Pull request closed without merging**
