### PR TITLE
Allow apple_library to be imported as a module

### PR DESCRIPTION
**Pull request by nguyentruongtho**
This PR will enable Swift target to be able to import apple_library. Quite a few things are imported from https://github.com/facebook/buck/pull/842

### CODE REVIEW

**Comment by ryu2** [comment]
```
java.lang.IllegalArgumentException: resource modulemap.st relative to com.facebook.buck.cxx.HeaderSymlinkTreeWithHeaderMap not found.
```

@nguyentruongtho  This failure seems related, can you check?

**Comment by stowy** [comment]
@nguyentruongtho this is great, thanks for doing.

I have tested interop with this here - https://github.com/stowy/buck_swift_test/tree/moduleTests - check the readme. 

I have found that swift does not recognize objC files in the module, unless they are specifically included in the modules bridging header.

I have also not been able to have external modules (eg a test module) reference an exported modules swift class from objc.

Are these results expected?

**Comment by nguyentruongtho** [comment]
> I have found that swift does not recognize objC files in the module, unless they are specifically included in the modules bridging header.

Yes, this is how module works, your headers need to be in exported header (public headers) for other module to use it.

> I have also not been able to have external modules (eg a test module) reference an exported modules swift class from objc.
This will come in follow on PR.

**Comment by nguyentruongtho** [comment]
My gos, problem with Windows again.

**Comment by stowy** [comment]
Thanks Tho, just to clarify about the reading objC from swift though, I meant that it will not read any objC classes in swift, even if those classes are in exported headers in the generated umbrella header. 

They will only be recognized if the headers are included in the objc-swift bridging header of the apple-library, which is unrelated to the module umbrella header.

Good news about the swift-objc interior, thanks.

**Comment by nguyentruongtho** [comment]
@stowy sure, I'll test your sample project once I get a CI pass for this PR  😄

**Comment by stowy** [comment]
No problems. Not a big issue with this PR, but definitely I would like to
address in future PRs.

Good luck with CI 😝

**Comment by ryu2** [comment]
I'm still getting a failure in `CompilationDatabaseIntegrationTest` under `testCreateCompilationDatabaseForAppleBinaryWithDeps`

**Comment by nguyentruongtho** [comment]
@ryu2 you mean facebook internal CI or on your machine? what is the error message and traces? It is passing for me locally and also passed 2 CI checks with Travis & CircleCI. I'm in blind now, could you have a look at it?

**Comment by ryu2** [comment]
@nguyentruongtho On my machine and the internal CI.  I'm running Xcode 8.1, how about you?  This might have something to do with it.

**Comment by ryu2** [comment]
```
   [junit] Testsuite: com.facebook.buck.apple.CompilationDatabaseIntegrationTest
    [junit] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3.761 sec
    [junit]
    [junit] Testcase: testCreateCompilationDatabaseForAppleLibraryWithNoDeps took 2.841 sec
    [junit] 	FAILED
    [junit]
    [junit] Expected: <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -fPIC, -fPIC, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Libraries/EXExample/EXExample#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/dep.tmp, Libraries/EXExample/EXExample/EXExampleModel.m, -o, buck-out/gen/Libraries/EXExample/EXExample#compile-pic-EXExampleModel.m.o7063e286,iphonesimulator-x86_64/EXExample/EXExampleModel.m.o]>
    [junit]      but: was <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -fPIC, -fPIC, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Libraries/EXExample/EXExample#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/dep.tmp, Libraries/EXExample/EXExample/EXExampleModel.m, -o, buck-out/gen/Libraries/EXExample/EXExample#compile-pic-EXExampleModel.m.o7063e286,iphonesimulator-x86_64/EXExample/EXExampleModel.m.o]>
    [junit] junit.framework.AssertionFailedError:
    [junit] Expected: <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -fPIC, -fPIC, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Libraries/EXExample/EXExample#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/dep.tmp, Libraries/EXExample/EXExample/EXExampleModel.m, -o, buck-out/gen/Libraries/EXExample/EXExample#compile-pic-EXExampleModel.m.o7063e286,iphonesimulator-x86_64/EXExample/EXExampleModel.m.o]>
    [junit]      but: was <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -fPIC, -fPIC, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Libraries/EXExample/EXExample#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path3195316497910570628/dep.tmp, Libraries/EXExample/EXExample/EXExampleModel.m, -o, buck-out/gen/Libraries/EXExample/EXExample#compile-pic-EXExampleModel.m.o7063e286,iphonesimulator-x86_64/EXExample/EXExampleModel.m.o]>
    [junit] 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    [junit] 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
    [junit] 	at com.facebook.buck.apple.CompilationDatabaseIntegrationTest.assertFlags(CompilationDatabaseIntegrationTest.java:315)
    [junit] 	at com.facebook.buck.apple.CompilationDatabaseIntegrationTest.testCreateCompilationDatabaseForAppleLibraryWithNoDeps(CompilationDatabaseIntegrationTest.java:117)
    [junit]
    [junit] Testcase: testCreateCompilationDatabaseForAppleBinaryWithDeps took 0.898 sec
    [junit] 	FAILED
    [junit]
    [junit] Expected: <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Apps/Weather/Weather#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/dep.tmp, Apps/Weather/Weather/EXViewController.m, -o, buck-out/gen/Apps/Weather/Weather#compile-EXViewController.m.ob61ea5f6,iphonesimulator-x86_64/Weather/EXViewController.m.o]>
    [junit]      but: was <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Apps/Weather/Weather#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/dep.tmp, Apps/Weather/Weather/EXViewController.m, -o, buck-out/gen/Apps/Weather/Weather#compile-EXViewController.m.ob61ea5f6,iphonesimulator-x86_64/Weather/EXViewController.m.o]>
    [junit] junit.framework.AssertionFailedError:
    [junit] Expected: <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Apps/Weather/Weather#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/dep.tmp, Apps/Weather/Weather/EXViewController.m, -o, buck-out/gen/Apps/Weather/Weather#compile-EXViewController.m.ob61ea5f6,iphonesimulator-x86_64/Weather/EXViewController.m.o]>
    [junit]      but: was <[/private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', '-std=gnu11', -Wno-deprecated, -Wno-conversion, -isysroot, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -arch, x86_64, '-mios-simulator-version-min=8.0', -I, buck-out/gen/Apps/Weather/Weather#iphonesimulator-x86_64,private-headers.hmap, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64.hmap, -I, buck-out, -I, buck-out/gen/Libraries/EXExample/EXExample#headers,iphonesimulator-x86_64, -F, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/xcode-developer-dir/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks, -Xclang, -fdebug-compilation-dir, -Xclang, .///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////, -x, objective-c, -c, -MD, -MF, /private/var/folders/79/r8x23p3x5z962kr42g6qfnt0x713m8/T/junit-temp-path5735745041404018234/dep.tmp, Apps/Weather/Weather/EXViewController.m, -o, buck-out/gen/Apps/Weather/Weather#compile-EXViewController.m.ob61ea5f6,iphonesimulator-x86_64/Weather/EXViewController.m.o]>
    [junit] 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    [junit] 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
    [junit] 	at com.facebook.buck.apple.CompilationDatabaseIntegrationTest.assertFlags(CompilationDatabaseIntegrationTest.java:315)
    [junit] 	at com.facebook.buck.apple.CompilationDatabaseIntegrationTest.testCreateCompilationDatabaseForAppleBinaryWithDeps(CompilationDatabaseIntegrationTest.java:204)
    [junit]

BUILD FAILED
/Users/markwang/devtools/buck/build.xml:612: Test com.facebook.buck.apple.CompilationDatabaseIntegrationTest failed
```

**Comment by nguyentruongtho** [comment]
ok, we are having issue with 8.1 internally, so we can't upgrade to use it yet. I'll download it later once I get to my office today. Still, it'd be helpful to know the error message that you are getting.

**Comment by nguyentruongtho** [comment]
If there are only 2 failing test cases left, then they should be fixed now. Really have no idea why it passed before.

**Comment by ryu2** [comment]
Still getting this due to the `buck-out/gen/library_with_header#default,headers` being added:

```
    [junit] Testsuite: com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest
    [junit] Tests run: 6, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 16.89 sec
    [junit]
    [junit] Testcase: testCompilationDatabase took 6.908 sec
    [junit] 	FAILED
    [junit] expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/test#default,headers -]Xclang -fdebug-compi...>
    [junit] junit.framework.AssertionFailedError: expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/test#default,headers -]Xclang -fdebug-compi...>
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.assertHasEntry(CxxCompilationDatabaseIntegrationTest.java:536)
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.testCompilationDatabase(CxxCompilationDatabaseIntegrationTest.java:247)
    [junit]
    [junit] Testcase: binaryWithDependenciesCompilationDatabase took 1.455 sec
    [junit] 	FAILED
    [junit] expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/library_with_header#default,headers -]Xclang -fdebug-compi...>
    [junit] junit.framework.AssertionFailedError: expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/library_with_header#default,headers -]Xclang -fdebug-compi...>
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.assertHasEntry(CxxCompilationDatabaseIntegrationTest.java:536)
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.binaryWithDependenciesCompilationDatabase(CxxCompilationDatabaseIntegrationTest.java:122)
    [junit]
    [junit] Testcase: testUberCompilationDatabase took 1.266 sec
    [junit] 	FAILED
    [junit] expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/test#default,headers -]Xclang -fdebug-compi...>
    [junit] junit.framework.AssertionFailedError: expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/test#default,headers -]Xclang -fdebug-compi...>
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.assertHasEntry(CxxCompilationDatabaseIntegrationTest.java:536)
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.testUberCompilationDatabase(CxxCompilationDatabaseIntegrationTest.java:312)
    [junit]
    [junit] Testcase: compilationDatabaseFetchedFromCacheAlsoFetchesSymlinkTreeOrHeaderMap took 2.935 sec
    [junit] Testcase: libraryCompilationDatabase took 1.436 sec
    [junit] 	FAILED
    [junit] expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/library_with_header#default,headers -]Xclang -fdebug-compi...>
    [junit] junit.framework.AssertionFailedError: expected:<...s.hmap -I buck-out -[]Xclang -fdebug-compi...> but was:<...s.hmap -I buck-out -[I buck-out/gen/library_with_header#default,headers -]Xclang -fdebug-compi...>
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.assertHasEntry(CxxCompilationDatabaseIntegrationTest.java:536)
    [junit] 	at com.facebook.buck.cxx.CxxCompilationDatabaseIntegrationTest.libraryCompilationDatabase(CxxCompilationDatabaseIntegrationTest.java:186)
    [junit]
    [junit] Testcase: compilationDatabaseWithDepsFetchedFromCacheAlsoFetchesSymlinkTreeOrHeaderMapOfDeps took 2.849 sec
```

**Comment by nguyentruongtho** [comment]
So, after a few ping/pong with fb peeps about failure of the tests on their internal CI, but they passed on both github CI and my local. I found out that if you run `ant test`, it will stop at the first failing unit test you get, which is bad, since sometimes, due to environment differences, random tests might fails, even they are not relate to your changes.

We should run `ant test -Dtest.haltonfailure=false` instead, in fact, I'm thinking about we should change the default behavior of `ant test` not to halt on failure.

**Comment by nguyentruongtho** [comment]
Travis fails because of Android tests, I'm sure this PR is perfect now.

**Comment by ryu2** [comment]
```
    [junit] @testable import SwiftCallsComplexObjC
    [junit]                  ^
    [junit] swift/Foo+Greeting.swift:1:11: error: use of undeclared type 'Foo'
    [junit] extension Foo {
    [junit]           ^~~
    [junit] swift/FooTest.swift:8:41: error: use of unresolved identifier 'Foo'
    [junit]         XCTAssertEqual("Hello, World!", Foo().greeting())
    [junit]                                         ^~~
    [junit] Swift.Bool:41:15: note: did you mean 'Bool'?
    [junit] public struct Bool {
    [junit]               ^
    [junit]
    [junit]
    [junit] BUILD FAILED: //:SwiftCallsComplexObjC#dwarf,iphonesimulator-x86_64,mach-o-bundle,swift-compile failed with exit code 1:
```

when I do `ant test -Dtest.class=SwiftTestIOSIntegrationTest`

**Comment by ryu2** [comment]
Since we don't have public Mac CI yet, most of the Swift stuff still needs to be locally tested.

**Comment by nguyentruongtho** [comment]
I didn't notice that, but I think it has many good reasons to fail. The test was setup incorrectly in https://github.com/facebook/buck/pull/911.

AFAIK, a test target cannot be a module, therefore importing like this [`#import import "SwiftCallsComplexObjC/Foo.h"`](https://github.com/facebook/buck/blob/master/test/com/facebook/buck/swift/testdata/swift_calls_complex_objc/Foo-Bridging-Header.h#L1)  is wrong.

I am going to revert https://github.com/facebook/buck/pull/911 as I think that PR https://github.com/facebook/buck/pull/911 is doing wrongly. It tries to fix a problem using header maps but it should use module (has a module map with umbrella header) instead. If there is no offend from @fkorotkov. 

The correct way of doing it should come after this PR. 

/cc @rmaz

**Comment by fkorotkov** [comment]
@nguyentruongtho SGTM.

**Comment by ryu2** [comment]
@facebook-github-bot shipit

**Comment by nguyentruongtho** [comment]
any output that I can see, /cc @mzlee if you find a reproduceable steps.

**Comment by ryu2** [comment]
https://gist.github.com/ryu2/4727f513a5064244ef2711f4656c27e5

has the stack trace.  It basically can't find a boost header `accumulators.hpp` which is a cross-cell target.

The issue is that `perf_test_hg.py` renames the repo directory temporarily, which invalidates all symlinks in header trees. Before, this test was still passing, presumably because we were using header maps for boost. For some reason this diff breaks this.

**Comment by ryu2** [comment]
It's an internal app, but you can try to repro it as follows with whatever app you have (not sure of the exact conditions yet needed for this error to occur):

From your repo dir (e.g. `repo`)

```
rm -rf buck-out
buck build -v 3 --config cache.mode=dir --config cache.dir=/tmp/buck-cache --deep <target>
```

Rename `repo` to something else, e.g. `_repo`

Then from `_repo`
```
buck clean
buck build -v 3 --config cache.mode=dir --config cache.dir=/tmp/buck-cache --deep <target>
```

**Comment by nguyentruongtho** [comment]
Just updated with some architecture changes for creating module map, the bug caught by your internal CI has not yet been addressed.

**Comment by ryu2** [comment]
Will be broken up into smaller PRs.

**Pull request closed without merging**
