### PR TITLE
Enables mixed kotlin + java integration tests.

### LINKED ISSUE #1371: Un-ignore mixed sources tests when kotlin 1.1.3 is released.
kotlin 1.1.3 includes support for passing java files. We can un-ignore the ignored mixed sources tests when the final version of the compiler is released.

### PR DESCRIPTION
**Pull request by dsyang**
This also bumps the kotlin version to 1.1.3.
Fixes #1371

### CODE REVIEW

**Comment by kageiit** [comment]
@dsyang A suggestion, kapt seems to work correctly only with the kotlin-compiler-embeddable.jar so might as well just use that and avoid having to add in a massive binary again in a future change

**Comment by runningcode** [comment]
@dsyang If i rename `test/com/facebook/buck/jvm/kotlin/testdata/kotlin_library_description/com/example/mixed/BUCK.fixture` to `BUCK` 

and then run 
`./bin/buck build test/com/facebook/buck/jvm/kotlin/testdata/kotlin_library_description/com/example/mixed:example` 

it seems to work, but when I run the test locally, 
`./bin/buck test //test/com/facebook/buck/jvm/kotlin:kotlin` 
it fails in the same way as CI.

**Comment by dsyang** [comment]
@runningcode That's really weird.... lemme try and figure it out

**Comment by kageiit** [comment]
Any update on this? @dsyang

**Comment by brettwooldridge** [comment]
@dsyang Is this pull request dead?

**Comment by cwoodwar6** [comment]
The bump to 1.1.3 will be required if we want to use the latest kapt arguments. Anyone have any ideas why this is failing?

**Comment by runningcode** [comment]
If I remember correctly, my theory as to why this was failing was that the kotlin compiler only likes the gradle directory structure.
This test passes correctly in the okbuck repository and in Square's uses but not here because the directory structure is different.

**Comment by ttsugriy** [comment]
this is still failing. You can repro it by running buck test //test/com/facebook/buck/jvm/kotlin:kotlin --filter KotlinLibraryIntegrationTest#shouldCompileLibraryWithDependencyOnAnother

Full output:
```
Build should have succeeded. Expected exit code 0 but was 1.
stacktrace: java.lang.AssertionError: Build should have succeeded. Expected exit code 0 but was 1.
	at org.junit.Assert.fail(Assert.java:88)
	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertExitCode(ProjectWorkspace.java:855)
	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertSuccess(ProjectWorkspace.java:820)
	at com.facebook.buck.jvm.kotlin.KotlinLibraryIntegrationTest.shouldCompileLibraryWithDependencyOnAnother(KotlinLibraryIntegrationTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.facebook.buck.testrunner.SameThreadFailOnTimeout.lambda$new$3(SameThreadFailOnTimeout.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

stderr: Oct 07, 2017 8:41:58 PM com.facebook.buck.log.Logger warn
WARNING: Could not execute xcode-select, continuing without developer dir.
Oct 07, 2017 8:41:58 PM com.facebook.buck.log.Logger info
INFO: HangMonitorAutoStart
Oct 07, 2017 8:41:59 PM com.facebook.buck.log.Logger warn
WARNING: Could not execute xcode-select, continuing without developer dir.
Oct 07, 2017 8:41:59 PM oshi.util.FileUtil readFile
WARNING: File not found: /proc/48243/stat
Oct 07, 2017 8:41:59 PM oshi.util.FileUtil readFile
WARNING: File not found: /proc/48391/stat
Oct 07, 2017 8:41:59 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Build started at %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger info
INFO: ActionGraph cache miss. Cache was empty.
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: ActionGraph cache assignment. skipActionGraphCache? %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
WARNING: Attempting to add absolute path to rule key. Only using file name: %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger warn
WARNING: Buck encountered an internal error
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:152)
	at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:87)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1752)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1705)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipelineStage.run(BuildRulePipelinesRunner.java:230)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipeline.run(BuildRulePipelinesRunner.java:152)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$1.run(BuildRulePipelinesRunner.java:103)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$6(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$4(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:143)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(parseCommandLineArguments.kt:63)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	... 21 more
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

    When running <kotlinc>.
    When building rule //com/example/good:example.
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Build finished at %s
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Awaiting termination of %s executor service. Waiting for all jobs to complete, or up to maximum of %s seconds...
Oct 07, 2017 8:42:01 PM com.facebook.buck.log.Logger logAppendableLogRecord
INFO: Failed cleaning log directory. It's possible another concurrent buck command removed the file. Error: %s
=== Build should have succeeded. Expected exit code 0 but was 1. ===
=== STDERR ===
PARSING BUCK FILES... 0.9s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.1s
Buck encountered an internal error
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:152)
	at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:87)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1752)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1705)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipelineStage.run(BuildRulePipelinesRunner.java:230)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipeline.run(BuildRulePipelinesRunner.java:152)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$1.run(BuildRulePipelinesRunner.java:103)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$6(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$4(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:143)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(parseCommandLineArguments.kt:63)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	... 21 more
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

    When running <kotlinc>.
    When building rule //com/example/good:example.
DOWNLOADED 0.00 BYTES/SEC AVG, 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 1.9s (100%) 1/2 JOBS, 1 UPDATED, 50.0% CACHE MISS
BUILD FAILED

=== STDOUT ===


====ERROR LOGS====

[2017-10-07 20:41:58.803][warn ][tid:21][com.facebook.buck.apple.AppleConfig] Could not execute xcode-select, continuing without developer dir.
[2017-10-07 20:41:59.238][warn ][tid:21][com.facebook.buck.apple.AppleConfig] Could not execute xcode-select, continuing without developer dir.
[2017-10-07 20:41:59.487][warn ][tid:29][oshi.util.FileUtil] File not found: /proc/48243/stat
[2017-10-07 20:41:59.494][warn ][tid:29][oshi.util.FileUtil] File not found: /proc/48391/stat
[2017-10-07 20:42:01.521][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-runtime.jar
[2017-10-07 20:42:01.559][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-compiler.jar
[2017-10-07 20:42:01.783][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-runtime.jar
[2017-10-07 20:42:01.784][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-compiler.jar
[2017-10-07 20:42:01.821][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-runtime.jar
[2017-10-07 20:42:01.822][warn ][tid:35][com.facebook.buck.rules.keys.RuleKeyBuilder] Attempting to add absolute path to rule key. Only using file name: /tmp/junit-temp-path5993152936061993787/kotlinc/lib/kotlin-compiler.jar
[2017-10-07 20:42:01.935][warn ][tid:33][com.facebook.buck.event.listener.LoggingBuildListener] Buck encountered an internal error
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:152)
	at com.facebook.buck.jvm.kotlin.KotlincStep.execute(KotlincStep.java:87)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.executeCommandsNowThatDepsAreBuilt(CachingBuildRuleBuilder.java:1752)
	at com.facebook.buck.rules.CachingBuildRuleBuilder$BuildRuleSteps.run(CachingBuildRuleBuilder.java:1705)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipelineStage.run(BuildRulePipelinesRunner.java:230)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$BuildRulePipeline.run(BuildRulePipelinesRunner.java:152)
	at com.facebook.buck.rules.BuildRulePipelinesRunner$1.run(BuildRulePipelinesRunner.java:103)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submit$6(WeightedListeningExecutorService.java:104)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$submitWithSemaphore$4(WeightedListeningExecutorService.java:78)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:988)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.buck.jvm.kotlin.JarBackedReflectedKotlinc.buildWithClasspath(JarBackedReflectedKotlinc.java:143)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at org.jetbrains.kotlin.cli.common.arguments.ParseCommandLineArgumentsKt.parseCommandLineArguments(parseCommandLineArguments.kt:63)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	... 21 more
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

    When running <kotlinc>.
    When building rule //com/example/good:example.

stdout:

stderr:
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
```

**Comment by thalescm** [comment]
@runningcode by gradle directory structure you mean having `src/main/(kotlin|java)` before the actual package? If so, I could compile only with command line args (no gradle involved) a structure different than gradle's default one (you can see [here](https://github.com/thalescm/kapt-cli)).  
The compiler not liking it different doesn't make sense, as `buck build ...` (by removing the .fixture) works and `buck test ...` don't (as you said). What makes you think that?  

@dsyang did you have time to check on this again?

**Pull request closed without merging**
