### PR TITLE
Added interop tests and fixed header map for Swift step

### PR DESCRIPTION
**Pull request by stowy**
Fixes issue: https://github.com/facebook/buck/issues/991

Probably needs a lot of tidy up and more tests but it's a start.

@nguyentruongtho

### CODE REVIEW

**Comment by nguyentruongtho** [comment]
Can you briefly explain about it, there is too many files to look into.

**Comment by stowy** [comment]
Sure sorry, the main change is at https://github.com/stowy/buck/blob/21d4cf21eacb3191c774973772b354db37043b51/src/com/facebook/buck/swift/SwiftDescriptions.java#L67

It changes the header map to be the shortened version of `{ 'HeaderPrefixPath/Filename.h' : 'absolute/path/to/file/filename.h'}` instead of what it is currently, which is `{ 'relative/path/to/Filename.h' : 'absolute/path/to/file/filename.h'}`.

**Comment by stowy** [comment]
The remainder of the change is to add an interop integration test (https://github.com/stowy/buck/blob/21d4cf21eacb3191c774973772b354db37043b51/test/com/facebook/buck/swift/InteropLibraryIntegrationTest.java#L41) which replicates issue https://github.com/facebook/buck/issues/991 - this passes on this branch but not in the main project.

**Comment by nguyentruongtho** [comment]
> Sure sorry, the main change is at https://github.com/stowy/buck/blob/21d4cf21eacb3191c774973772b354db37043b51/src/com/facebook/buck/swift/SwiftDescriptions.java#L67
It changes the header map to be the shortened version of { 'header_prefix_path/filename.h' : 'absolute/path/to/file/filename.h'} instead of what it is currently, which is { 'relative/path/to/filename.h' : 'absolute/path/to/file/filename.h'}. The former allows normal imports in ObjC, the latter breaks ObjC imports.

I think you are right, swift companion target should know about its parent `header_path_prefix` and should be able to search for its parent header during compilation. The approach looks good, I suggest you to create a simpler sample for the issue.

Since this is issue regarding headers, @ryu2 would know more. And also, there was some work on this part was done by @fkorotkov https://github.com/facebook/buck/pull/911. Are you guys reviewing this PR?

**Comment by nguyentruongtho** [comment]
You might not need this PR. Indeed, I'm finishing up something that could cover this case, and also the previous case https://github.com/facebook/buck/pull/911.

**Comment by fkorotkov** [comment]
Part about headers seems reasonable to me. Seems my logic had bugs for more complicated project structure.

**Pull request closed without merging**
