### PR TITLE
Don't add androidFacet.module_gen_path if disable_r_java_idea_generator is true

### PR DESCRIPTION
**Pull request by raviagarwal7**
Adding module_get_path somehow messes up R.java autocomplete in intellij

### CODE REVIEW

**Comment by kageiit** [comment]
cc @styurin

**Comment by styurin** [comment]
Could you provide more details about your problem including IntelliJ version and what kind of issues you are having?

I'm not really convinced that this is a right solution. The purpose of `autogenerate_sources` is to instruct IntelliJ to automatically generate `R.java` and other generated files vs. generate them manually. When these files are generated manually the folder with generated files should still be included as a content root.

**Comment by raviagarwal7** [comment]
sorry for the delay, I will get more details about the issue.

**Comment by styurin** [comment]
I'm going to close this PR for now. Please, re-open when needed.

**Pull request closed without merging**
