### PR TITLE
Reusing same classesDir for kapt and javac

### LINKED ISSUE #1897: AutoService generated META-INF files is not getting packages into the kotlin_library's output jar.
https://github.com/google/auto/tree/master/service

Works on a `java_library` jar but fails on `kotlin_library`.

### PR DESCRIPTION
**Pull request by thalescm**
Resolves #1897

### CODE REVIEW

**Comment by styurin** [comment]
Tests are broken

**Comment by thalescm** [comment]
Tests failure seems unrelated

**Comment by styurin** [comment]
Is that possible to add an integration test?

**Comment by thalescm** [comment]
@styurin done :)

**Comment by thalescm** [comment]
@styurin any news?

**Comment by thalescm** [comment]
The way of adding an integration for the test, without reimplementing AutoService would be to add it.

Could you provide an actual example (rule name) of a test who access resources on buck itself please, I can try to modify that part to minimize dependencies.

But reimplementing AutoService makes no sense, so would be either keeping the rest of the jars, or reverting those additions

**Comment by thalescm** [comment]
@styurin Should be better now if you could take another look :)

**Comment by styurin** [comment]
Just wanted to clarify, this change modifies an existing test that would fail if that change hadn't been introduced, right?

**Comment by thalescm** [comment]
@styurin Right,
By removing the file at `META-INF/services/` describing which annotation processor should be run, the tests begin to fail (as expected).

Even after adding AutoService (an annotation processor that automatically generates the aforementioned file for you), the tests continue to fail.

The change therefore solves the issue (and the tests that existed are still valid, with the addition of this new validation)

**Comment by thalescm** [comment]
@styurin Do you need any other changes for this PR?

**Comment by thalescm** [comment]
@styurin could you please take another look?

**Pull request closed without merging**
