### PR TITLE
add documentation for android_instrumentation_apk

### PR DESCRIPTION
**Pull request by tgummerer**

### CODE REVIEW

**Comment by sdwilsh** [comment]
Thanks so much for doing this.  This will be a big help :)

**Comment by tgummerer** [comment]
Thanks a lot for your review.  I updated the pull request :)

**Comment by sdwilsh** [comment]
Sorry it took me so long to get this review to you!  I've been out the past week.

**Comment by tgummerer** [comment]
No worries, there is no rush :) I updated the pull request.

**Comment by sdwilsh** [comment]
Thanks!

**Comment by sdwilsh** [comment]
Thanks again for your fix.  It made our weekly update post: https://www.facebook.com/buckbuildtool/posts/836733013063076

**Pull request closed without merging**
