### PR TITLE
Update dx from android tools

### PR DESCRIPTION
**Pull request by kageiit**
This updates `dx` to the code drop from android gradle plugin 2.2.0 located at

https://android.googlesource.com/platform/tools/base/+/gradle_2.2.0/build-system/builder/src/main/java/com/android

This version of dx has been modified by the android tools team to be able to run multiple invocations in process. Only slight modifications were made to keep the existing FB added functionality still intact like `computeReferencedResources`.

There might be some areas that we still want to keep from before for perf, but during profiling, the performance of dx is almost identical compared to the existing fork.

### CODE REVIEW

**Comment by dreiss** [comment]
Is there any urgency to this?

**Comment by kageiit** [comment]
> Is there any urgency to this?

no urgency. Just wanted to put it up so we can build and test on fb's and external users' projects.

**Comment by dreiss** [comment]
Are you able to separate this into two commits?  One that's the unmodified code, and one that's your local changes?  It's pretty much impossible to review as-is.

**Comment by dreiss** [comment]
This looks fine.  I want to take some time to make sure that changes in dx aren't going to interfere with any of our runtime optimizations (at FB).  If anyone's in a hurry to get this landed, let me know and I'll get it moving along faster.

**Comment by kageiit** [comment]
> This looks fine. I want to take some time to make sure that changes in dx aren't going to interfere with any of our runtime optimizations (at FB)

redex is used outside of fb already on apks (and their dex files) that are produced by this version of dx out in the wild already. I would be surprised if this regressed anything majorly :)

**Comment by kageiit** [comment]
Any update on this?

**Comment by dreiss** [comment]
Okay, this is working fine with redex on our apps as well.  I'm going to land it.

This will be the first non-squashed stack I've imported from GitHub, so bear with me.

**Comment by dreiss** [comment]
Oh, I found a problem: this spews the merge report onto the console.  Any idea why that wasn't happening before?

**Comment by kageiit** [comment]
> Oh, I found a problem: this spews the merge report onto the console. Any idea why that wasn't happening before?

Should be fixed now

**Comment by dreiss** [comment]
I pulled these in, tweaked them a bit, and landed.  Maybe we should leave this PR open for a few days so we can make sure that we don't need to revert it.

**Comment by kageiit** [comment]
@dreiss if everything looks stable, can we please close this PR?

**Comment by dreiss** [comment]
Looking good on our end.

**Pull request closed without merging**
