### PR TITLE
Bump JaCoCo to 0.7.5

### PR DESCRIPTION
**Pull request by somechris**
Summary:
By bumping JaCoCo to 0.7.5, JaCoCo's exec file format version gets
bumped from 1006 to 1007, and we can use current tools to analyze
the jacoco.exec again.

### CODE REVIEW

**Comment by sdwilsh** [comment]
I can't apply this cleanly, and when I did what I thought was redoing the work, I got this error when actually running tests with code coverage enabled:

```Error occurred during initialization of VM
agent library failed to init: instrument```

Can you rebase and retest you changes?  Can you also add the source jar of the agent while you are here?

**Comment by somechris** [comment]
> I can't apply this cleanly, [...]
> Can you rebase and retest you changes?

I rebased the PR.

Testing using the buck test suite is a bit tricky, as Travis is failing on current master (before my PR).
'ant test' is also already failing on current master (before my PR).

(FWIW ... 'ant test' is still failing the same tests in exactly the same way after my PR.)

But buck builds just fine with my patch sets.
And running it on test projects works out just fine.
Also the generated jacoco.exec is fine and usable.
Also the generated JaCoCo reports are fine.

(Both on JDK 7 and JDK 8)

> `Error occurred during initialization of VM agent library failed to init: instrument`

This error message never showed up for me.
How can I reproduce it?

> Can you also add the source jar of the agent while you are here?

Done.
(The `jacocoagent.jar` belongs to the `org.jacoco.agent` artifactId,
hence the `org.jacoco.agent-0.7.5.201505241946-sources.jar` are the
sources for both `org.jacoco.agent-0.7.5.201505241946.jar` and
`jacocoagent.jar`.)

**Comment by sdwilsh** [comment]
Travis keeps failing because it's killing us while we build.  I've actually disabled it recently.

It's possible I messed something up when trying to rebase your diff, so let me see if the updated version just works :)

**Comment by sdwilsh** [comment]
Thanks :)

**Comment by sdwilsh** [comment]
Thanks again for your fix.  It made our weekly update post: https://www.facebook.com/buckbuildtool/posts/836733013063076

**Pull request closed without merging**
