### PR TITLE
Use absolute paths for DERIVED_FILE_DIR

### PR DESCRIPTION
**Pull request by dfed**
If a `.mlmodel` is added to an Xcode target where that module's `DERIVED_FILE_DIR` is set to a relative path, Xcode will crash.

This PR sets `DERIVED_FILE_DIR` to be an absolute path, which allows `.mlmodel`s to be included in generated Xcode projects without Xcode crashing.

### CODE REVIEW

**Comment by dfed** [comment]
Friendly bump for a review 🙂

**Comment by styurin** [comment]
There are some legitimate errors in Travis CI

**Comment by dfed** [comment]
Looks like I need to update com.facebook.buck.features.apple.project.ProjectGeneratorTest. Will do so and circle back.

**Comment by dfed** [comment]
`ProjectGeneratorTest` is now passing after I updated the unit test to test the new behavior @styurin.

**Pull request closed without merging**
