### PR TITLE
upgrade okhttp to 3.3.0

### PR DESCRIPTION
**Pull request by yschimke**
- general good health (security fixes)
- makes http/2 caching more viable
- supports java 9

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @ruibm, @sdwilsh and @andrewjcg to be potential reviewers.

**Comment by yschimke** [comment]
I need to fix a mocking test broken by a final class

Cannot subclass final class class okhttp3.OkHttpClient$Builder

**Comment by Coneko** [comment]
What test is it? We have some helper classes for tests so that mocking is usually not necessary.

**Comment by yschimke** [comment]
It was failing with a NPE with the diff in this PR, I guess smart mocks return null rather than failing on final classes?

I made the following edit and that's when it gave me the error above.

```
diff --git a/test/com/facebook/buck/slb/ClientSideSlbTest.java b/test/com/facebook/buck/slb/ClientSideSlbTest.java
index 4d58bce..0059687 100644
--- a/test/com/facebook/buck/slb/ClientSideSlbTest.java
+++ b/test/com/facebook/buck/slb/ClientSideSlbTest.java
@@ -50,6 +50,7 @@ public class ClientSideSlbTest {
   private BuckEventBus mockBus;
   private Clock mockClock;
   private OkHttpClient mockClient;
+  private OkHttpClient.Builder mockClientBuilder;
   private ScheduledExecutorService mockScheduler;
   private ClientSideSlbConfig config;

@@ -63,6 +64,7 @@ public class ClientSideSlbTest {
     mockBus = EasyMock.createNiceMock(BuckEventBus.class);
     mockFuture = EasyMock.createMock(ScheduledFuture.class);
     mockClient = EasyMock.createNiceMock(OkHttpClient.class);
+    mockClientBuilder = EasyMock.createNiceMock(OkHttpClient.Builder.class);
     mockScheduler = EasyMock.createMock(ScheduledExecutorService.class);
     mockClock = EasyMock.createMock(Clock.class);
     EasyMock.expect(mockClock.currentTimeMillis()).andReturn(42L).anyTimes();
@@ -81,6 +83,8 @@ public class ClientSideSlbTest {
   @SuppressWarnings("unchecked")
   public void testBackgroundHealthCheckIsScheduled() {
     Capture<Runnable> capture = EasyMock.newCapture();
+    EasyMock.expect(mockClient.newBuilder()).andReturn(mockClientBuilder);
+    EasyMock.expect(mockClientBuilder.build()).andReturn(mockClient);
     EasyMock.expect(mockScheduler.scheduleWithFixedDelay(
         EasyMock.capture(capture),
         EasyMock.anyLong(),
@@ -101,6 +105,8 @@ public class ClientSideSlbTest {
   @SuppressWarnings("unchecked")
   public void testAllServersArePinged() throws IOException {
     Capture<Runnable> capture = EasyMock.newCapture();
+    EasyMock.expect(mockClient.newBuilder()).andReturn(mockClientBuilder);
+    EasyMock.expect(mockClientBuilder.build()).andReturn(mockClient);
     EasyMock.expect(mockScheduler.scheduleWithFixedDelay(
         EasyMock.capture(capture),
         EasyMock.anyLong(),
```

Apologies for the non working PR, but any advice on how to fix would be much appreciated.

**Comment by ruibm** [comment]
Hum, this is quite annoying from the latest OkHttpClient. :(

Let me take a quick look at what is the least evasive way of sorting this out without too many changes.

**Comment by yschimke** [comment]
@ruibm I realize this PR was unprompted, so thanks for the advice here.

**Comment by ruibm** [comment]
The PR seems fine @yschimke. I'll make the fix for the test and push it in tomorrow. Thanks.

**Comment by yschimke** [comment]
okhttp 3.3.0 just got released yesterday, do you want me to adjust to include that also.  Or hold off since its so new, and the bigger change it 2 -> 3?

**Comment by ruibm** [comment]
Still doesn't seem to be in maven however if you are up to adding the new jar versions to your PR I can still include it in this push.

**Comment by yschimke** [comment]
It's there http://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.3.0/

I'll push a new version in a few minutes.  I hope you don't mind if I let travis point out additional test failures, compile worked for //test/... but I get a lot of spurious failures if I run "./bin/buck test //test/...", but the individual failing targets work.

**Comment by facebook-github-bot-4** [comment]
@yschimke updated the pull request.

**Comment by ruibm** [comment]
Cool thanks! I've pulled your updates now.

**Pull request closed without merging**
