### PR TITLE
don't hide bitcode symbols

### PR DESCRIPTION
**Pull request by rmaz**
Currently it is not possible to link watch apps as the `-bitcode_symbol_map` flag requires a path. I took a look for a good place to put a path for this, but it seems better handled in the BUCK files for now.

#1547

### CODE REVIEW

**Comment by ttsugriy** [comment]
@dinhviethoa could you please take a look with your expert iOS knowledge

**Comment by rmaz** [comment]
any movement on this one?

**Comment by yiding** [comment]
@ryu2 do you recall why you set these flags? your commit did not provide any rationale for these flags.

**Comment by ryu2** [comment]
IIRC, this was what Xcode adds automatically in its WatchOS builds, or was at the time of the original commit.  Since Apple's App Store validation is a bit of a black box, I wanted to play it safe and replicate Xcode's flags as much as possible.

@rmaz If you've built and successfully submitted an app to Apple with this change, then sure.

**Comment by rmaz** [comment]
Thanks for merging this one in.

> IIRC, this was what Xcode adds automatically in its WatchOS builds

This is what is added automatically by Xcode when archiving, but it also adds a path for the bitcode symbol map to be placed at, which is required. Its equivalent to stripping more or less, but has to happen at link time, so unfortunately is not a great fit for bucks existing strip flavour approach. I could not see an obvious place to add this without adding a whole new flavour, so it seemed more sensible to just omit the flags for now and let users add them for their own release builds. This at least makes it possible to link a watch binary, and matches what users have to do for any iOS app with bitcode enabled.

> However, if you need to add those flags to the BUCK file in order for a app to pass validation, then we will have to make sure this change doesn't break releases.

I don't believe this is required to pass validation, but desirable for sure. Open to suggestions for the best way of getting this implemented. The same issue applies to all app store apps, not just watch apps, so we should come up with a clean way of handling this in general. IMO the only way to get this done is by adding a `bitcode` flavour, which we could use to apply the correct compiler and linker flags and output the symbol map next to the dSYM. Then the flavour could be applied separately for release builds, avoiding slowing down debug builds and so on. Thoughts?

**Comment by dinhviethoa** [comment]
I think you need to rebase and then we can land it.

**Comment by rmaz** [comment]
Oh, misunderstood the phab import message, rebased now

**Comment by dinhviethoa** [comment]
Could you fix the following unit test?
//test/com/facebook/buck/apple:apple_test_integration - watchApplicationBundle (com.facebook.buck.apple.AppleBundleIntegrationTest) (platform: macosx)

To reproduce:
buck test //test/com/facebook/buck/apple:apple_test_integration --filter AppleBundleIntegrationTest#watchApplicationBundle

**Comment by rmaz** [comment]
Tricky, looks like all tests requiring code signing have been disabled. I'll just pull out this test for now, doesn't seem possible to validate as this only applies to device builds.

**Pull request closed without merging**
