### PR TITLE
Update jitpack to use python 3

### LINKED ISSUE #2387: Jitpack build broken due to python3 switch
Sample log: https://jitpack.io/com/github/facebook/buck/3e23794873/build.log

Relevant lines:
```bash
BUILD SUCCESSFUL
Total time: 1 minute 7 seconds
+++ bin/buck build buck --show-output
+++ awk '{print $2}'
Not using buckd because watchman isn't installed.
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
PARSING BUCK FILES: FINISHED IN 0.8s
CREATING ACTION GRAPH: FINISHED IN 0.1s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 1.1s
BUILD FAILED
No python interpreter found (searched python3).
    When creating rule //py/hash:hash_files.
++ PEX=
2020-02-08T06:34:20.044197191Z
Exit code: 1
```

### PR DESCRIPTION
**Pull request by kageiit**
Fixes #2387

### CODE REVIEW

**Comment by swgillespie** [comment]
Looks like there are some Python 3 problems in CI:

```
====STANDARD ERR====
=== Expected exit code 0 but was 5. ===
=== STDERR ===
Using additional configuration options from .buckconfig.local
Invalidating internal cached state: Watchman failed to start. This may cause slower builds.
PARSING BUCK FILES: FINISHED IN 0.3s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 0.3s
BUILD FAILED
Buck wasn't able to parse /private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/junit-temp-path4882346160650548078/BUCK:
AttributeError: 'dict' object has no attribute 'iteritems'
Call stack:
  File "python-dsl/buck_parser/buck.py", line 2048, in process_with_diagnostics
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/buck.py", line 1938, in process
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/buck.py", line 1926, in _process_build_file
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/profiler.py", line 507, in wrapped
    return func(*args, **kwargs)
  File "python-dsl/buck_parser/buck.py", line 1850, in _process
    exec(code, module.__dict__)
  File "/private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/junit-temp-path4882346160650548078/BUCK", line 6
    for target, flags in TARGETS.iteritems():


Buck wasn't able to parse /private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/junit-temp-path4882346160650548078/BUCK:
AttributeError: 'dict' object has no attribute 'iteritems'
Call stack:
  File "python-dsl/buck_parser/buck.py", line 2048, in process_with_diagnostics
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/buck.py", line 1938, in process
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/buck.py", line 1926, in _process_build_file
    package_implicit_load=package_implicit_load,
  File "python-dsl/buck_parser/profiler.py", line 507, in wrapped
    return func(*args, **kwargs)
  File "python-dsl/buck_parser/buck.py", line 1850, in _process
    exec(code, module.__dict__)
  File "/private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/junit-temp-path4882346160650548078/BUCK", line 6
    for target, flags in TARGETS.iteritems():
```

looks like we need to fix some tests - @v-jizhang have we seen these before failing in CI?

**Comment by v-jizhang** [comment]
@swgillespie Yes, I've noticed that. I've already submitted a diff D19894640.

**Comment by kageiit** [comment]
> @swgillespie Yes, I've seen that and I've already submitted a diff D19894640.

Do I need to do anything else here or can this be imported?

**Comment by v-jizhang** [comment]
@kageiit Please see the announcement #2401. This is the master branch and all PRs will be reviewed and merged on GitHub, no need to import.

**Pull request merged**
