### PR TITLE
Make apple_library build without objc source

### PR DESCRIPTION
**Pull request by nguyentruongtho**
Apparently, we can build `apple_library` share library even the target contains no objective-c source file.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
@nguyentruongtho updated the pull request - [view changes](https://github.com/facebook/buck/pull/895/files/20dd27efb26352abdb35907db6489e3984f8c3c7..2841cb5fffe65c93019fa19d7351e989085b98fc)

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3914036).

**Comment by facebook-github-bot-4** [comment]
@nguyentruongtho updated the pull request - [view changes](https://github.com/facebook/buck/pull/895/files/2841cb5fffe65c93019fa19d7351e989085b98fc..483318d7882f5902d5cf64422325051b480b615c) - [changes since last import](https://github.com/facebook/buck/pull/895/files/2841cb5fffe65c93019fa19d7351e989085b98fc..483318d7882f5902d5cf64422325051b480b615c)

**Comment by facebook-github-bot-7** [comment]
@nguyentruongtho updated the pull request - [view changes](https://github.com/facebook/buck/pull/895/files/483318d7882f5902d5cf64422325051b480b615c..1920b776a37b53f5dffbccd3875af93afeb8f932) - [changes since last import](https://github.com/facebook/buck/pull/895/files/483318d7882f5902d5cf64422325051b480b615c..1920b776a37b53f5dffbccd3875af93afeb8f932)

**Pull request closed without merging**
