### PR TITLE
Add new kotlin jars required during compilation from Kotlin 1.1.60

### PR DESCRIPTION
**Pull request by kageiit**
Compilation fails otherwise with class not found exceptions from kotlin 1.1.60 onwards

### CODE REVIEW

**Comment by kageiit** [comment]
cc @hzsweers @cwoodwar6 @artem-zinnatullin

**Comment by hzsweers** [comment]
Did you not need to handle the annotation processing jar?

**Comment by kageiit** [comment]
> Did you not need to handle the annotation processing jar?

Its not required for compilation. kapt support is being handled separately by @cwoodwar6 's kapt PR that will attach the jar as a compiler argument instead

**Comment by hzsweers** [comment]
The reason I ask is because our internal build failed due to okbuck trying
to download it, so I wasn't sure where in the pipeline that was happening

**Comment by kageiit** [comment]
> The reason I ask is because our internal build failed due to okbuck trying
> to download it, so I wasn't sure where in the pipeline that was happening

Thats handled separately in https://github.com/uber/okbuck/commit/00b96385c4879cace766894d20820866cc74d182

**Comment by hzsweers** [comment]
:+1: LGTM then

**Pull request closed without merging**
