### PR TITLE
Update genrule to indicate that it can handle directories.

### PR DESCRIPTION
**Pull request by nfisher**
See discussion here: https://groups.google.com/forum/#!topic/buck-build/uEbqiWczy6c

Not sure if I should update gh-pages branch as well?

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @alisdair04 to be a potential reviewer.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by sdwilsh** [comment]
I'll happily import this once you sign the CLA :)

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Comment by sdwilsh** [comment]
Looks like @Coneko already started this process actually :)

**Pull request closed without merging**
