### PR TITLE
Stop at -- when parsing verbosity.

### LINKED ISSUE #493: `buck run` parses -v after --
```shell
$ buck run src/com/facebook/buck/maven:resolver -- -v bye
[2015-11-03 16:42:41.701][error][command:169c085d-6632-40a2-b36b-0395103e3541][tid:14][com.facebook.buck.cli.Main] Uncaught exception at top level
java.lang.NumberFormatException: For input string: "bye"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.facebook.buck.cli.VerbosityParser.parse(VerbosityParser.java:44)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:429)
	at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1043)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1100)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:331)
```

### PR DESCRIPTION
**Pull request by mikekap**
Fixes #493; although not in the best way. I didn't want to find out why verbosity parsing is implemented as it currently is the hard way :X.

### CODE REVIEW

**Comment by mikekap** [comment]
@andrewjcg small ping - CI has been failing since 3a93fffa72ae850f6981ecd29ab2d1a4d09f2ac5 with python-inplace errors :(. I tried rebasing to the latest upstream, but the error is still there.

**Comment by andrewjcg** [comment]
@facebook-github-bot import

**Comment by sdwilsh** [comment]
I think @andrewjcg has a diff up to fix that test failure, so I'll go review that next.

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
