### PR TITLE
[apple_asset_catalog] Include Product Type in AcTool Args

### PR DESCRIPTION
**Pull request by ydxia**
Currently, building Messages extensions with buck will not generate the Messages app icon correctly. This is because in order to do so, `actool` needs to know what product type it is creating an asset catalog + app icon for.

This change funnels the product type from apple_bundle into AppleAssetCatalog and AcToolStep so that `actool` is called with `--product-type <product type>` (needs to be `com.apple.product-type.app-extension.messages` for Messages extensions).

### CODE REVIEW

**Comment by ydxia** [comment]
@v-jizhang can you take a look? 🙏

**Comment by v-jizhang** [comment]
@ydxia We are working on a change in buck open source, please see the announcement #2401. And we will get back to you soon. Thanks you.

**Comment by ydxia** [comment]
For my understanding, should changes target the `dev` branch then? The announcement references changes made by the "Facebook’s Build Infra team" for `dev`; does this impact how external contributions are merged?

**Comment by v-jizhang** [comment]
Yes, all PRs will be reviewed and merged here in the master branch. Only selected PRs can be ported to dev.

**Comment by ydxia** [comment]
ok so `dev` will contain experimental changes to infrastructure whereas bug fixes should still go to `master`?

**Comment by v-jizhang** [comment]
Bug fixes should be ported to dev too.

**Comment by ydxia** [comment]
hi - just pinging again here to get a sense of what the expected workflow is and if there's anything needed from my side. Thanks!

**Comment by v-jizhang** [comment]
Your PR looks good to me but we 're working on an Open Source plan. Thank you!

**Pull request merged**
