### PR TITLE
Add ARM64 support. Fixes facebook/buck#414

### PR DESCRIPTION
**Pull request by LegNeato**

### CODE REVIEW

**Comment by LegNeato** [comment]
I have signed the CLA. Seems to be a bug in the CLA tool (it's throwing an error). I'll email cla@fb.com.

**Comment by sdwilsh** [comment]
There was a bug before where we never prompted former employees to sign the individual CLA.  That bug has been fixed, but we don't have one of those on file for you.  @caabernathy should be able to help you after you email :)

**Comment by leeight** [comment]
https://github.com/facebook/react-native/issues/2814

**Comment by LegNeato** [comment]
If no one cleans this up, adds tests, and adds the right flags I will try to do it next week.

**Comment by Coneko** [comment]
Thanks!

**Comment by LegNeato** [comment]
FYI, the CLA has now been signed manually. Still need to find time to fix this up a bit...

**Comment by leeight** [comment]
@LegNeato `build` method signature changed, you need add more parameters.

**Comment by LegNeato** [comment]
Rebased on latest changes.

Also, I removed `arm64` from the list of default archs because currently the default platform is `android-9`, which doesn't have `arm64`. Happy to revisit that (either by adding it back in or adding it back in + bumping the default platform). Thoughts?

**Comment by marcinkosiba** [comment]
I'm a bit anxious about having no test coverage for this. Would it be possible to have an entry for this in https://github.com/facebook/buck/blob/1a5992e4592746c8bc5fdc8d7f82afcfc966c719/test/com/facebook/buck/cxx/CxxBinaryIntegrationTest.java#L1847
?

I think not having arm64 in the default set is OK for now.

**Comment by LegNeato** [comment]
Travis failure is unrelated:

```
FAIL    <100ms  0 Passed   0 Skipped   1 Failed   //test/com/facebook/buck/android:integration
FAILURE //test/com/facebook/buck/android:integration main: //test/com/facebook/buck/android:integration failed with exit code 137:
junit
stderr: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0

com.facebook.buck.step.StepFailedException: //test/com/facebook/buck/android:integration failed with exit code 137:
junit
stderr: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0

	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:63)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:65)
	at com.facebook.buck.step.DefaultStepRunner.lambda$0(DefaultStepRunner.java:84)
	at com.facebook.buck.step.DefaultStepRunner$$Lambda$246/748842359.call(Unknown Source)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$$Lambda$79/547201549.apply(Unknown Source)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by LegNeato** [comment]
Ok, I think we are ready to go here.

It doesn't feel really "nice" though. In order to build arm64 for android, you need to set the following in the `[ndk]` config section:

* `cpu_abis = arm64` -- because `arm64` is not in the [default arch set](https://github.com/facebook/buck/blob/1a5992e4592746c8bc5fdc8d7f82afcfc966c719/src/com/facebook/buck/android/NdkCxxPlatforms.java#L80), mainly due to the app platform default being [`android-9`](https://github.com/facebook/buck/blob/1a5992e4592746c8bc5fdc8d7f82afcfc966c719/src/com/facebook/buck/android/NdkCxxPlatforms.java#L79) 
* `app_platform = android-21` -- because `arm64` was not available before that, and again Buck's `app_platform` default is`android-9`

So to build `arm64`, your `[ndk]` section in `.buckconfig` needs to look like:
```ini
[ndk]
  # If you want all common ABIs. You could also do a subset.
  cpu_abis = armv7, arm64, x86, x86_64
  app_platform = android-21
  gcc_version = 4.9
  clang_version = 3.8
```
The last two lines shouldn't be needed as they should switch correctly ([gcc](https://github.com/facebook/buck/blob/1a5992e4592746c8bc5fdc8d7f82afcfc966c719/src/com/facebook/buck/android/NdkCxxPlatforms.java#L104), [clang](https://github.com/facebook/buck/blob/1a5992e4592746c8bc5fdc8d7f82afcfc966c719/src/com/facebook/buck/android/NdkCxxPlatforms.java#L111)), but can't hurt...

Note that this is not just required for `arm64`...it is also an issue with `x86_64` and to support that abi it needs to be configured the same way.

So the question is, is it better to have people make these changes, or is it better to have the default be these values and have the people needing to target older app platforms, compiler versions, and cpu_abis change *their* config?

**Pull request closed without merging**
