### PR TITLE
Disk IO timeout property

### PR DESCRIPTION
**Pull request by rmaz**
Ref #803. Make it possible to specify a custom disk IO executor timeout as a java property. This makes it possible to clean the cache on CI jobs while a better solution is found to fix the issue with the cache growing without bounds.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @beefon, @yiding and @ruibm to be potential reviewers.

**Comment by sdwilsh** [comment]
Wouldn't this be better set in the `.buckconfig`?

**Comment by marcinkosiba** [comment]
please make the timeout a setting on .buckconfig

**Comment by rmaz** [comment]
I'm going to close this one for now, we have got buckd working on our CI machines. I am not sure if this setting makes sense in .buckconfig though, it seems like something that shouldn't be customisable. Maybe when buckd is not enabled there should be no timeout? Or at least the task should run until at least some %age of the cache has been cleaned?

**Pull request closed without merging**
