### PR TITLE
Make proguard buck config support taking source target

### PR DESCRIPTION
**Pull request by raviagarwal7**

### CODE REVIEW

**Comment by styurin** [comment]
This change will add proguard target to the deps, but where is it used?

**Comment by raviagarwal7** [comment]
> This change will add proguard target to the deps, but where is it used?

`getProguardJarOverride` is the function which provides the `SourcePath` corresponding to the specified proguard target or progaurd jar path. The target is added to the deps to make sure it is built before the jar from `getProguardJarOverride` is used.

**Comment by raviagarwal7** [comment]
@styurin -- tests seems to have passed. could you please import this. thanks!

**Comment by kageiit** [comment]
@styurin any update on the import?

**Comment by kageiit** [comment]
Friendly Ping @styurin :)

**Pull request closed without merging**
