### PR TITLE
Minor TestNG fixes.

### PR DESCRIPTION
**Pull request by liuyang-li**
@jiangty-addepar

### CODE REVIEW

**Comment by liuyang-li** [comment]
@sdwilsh, separate pull-requests have been submitted for each of the logical changes.

**Comment by sdwilsh** [comment]
Thanks!

**Comment by liuyang-li** [comment]
I agree. Let me try and add SKIPPED ResultType.

**Comment by sdwilsh** [comment]
Any luck adding the skipped result type @liuyang-li?

**Comment by liuyang-li** [comment]
@sdwilsh , a SKIPPED result type already exists, which I was able to use.

I realized that: We need to pass on the timeout value from `.buckconfig` to testng, so that it will terminate for tests that run indefinitely. Let me separate out my changes for the test time out into another PR, and update this one.

**Comment by liuyang-li** [comment]
@sdwilsh , I just updated the change set to set the default time out value correctly. Let us do the changes for testng in phases.

I will submit another PR to update the default behavor for skipped tests in TestNGRunner. After that, I will refactor things a bit to move TestNG to its own package (it is under junit now, which is not correct). There are a couple of other fixes that I plan to do after that, e.g., correctly pass the filters to testng to select test classes.

In all, let us push this small change first.

**Pull request closed without merging**
