### PR TITLE
Add support to attach custom headers to buck doctor request

### PR DESCRIPTION
**Pull request by kageiit**
This allows attaching additional headers for auth as an example

### CODE REVIEW

**Comment by kageiit** [comment]
cc @styurin

**Comment by kageiit** [comment]
> please add a test to verify that this functionality actually works :)

@ttsugriy There are no existing tests that check the validity of args/headers. Whats the best way to test this, given its mostly looking like a smoke test

**Comment by ttsugriy** [comment]
@kageiit, looks like current code was not really written with testability in mind, which is very unfortunate. HttpClient should not be created in that method and instead passed to the method. This way you can create a `FakeHttpClient` that would capture everything that it was passed with. You can see suggestions on how to do this using interceptors in https://github.com/square/okhttp/issues/1096 but I'm ok with a plain old fake :) (just no mocks please).

While at it, please also add documentation for the configuration option you're adding :)

**Comment by linzhp** [comment]
@kageiit You can write integration tests similar to [this](https://github.com/facebook/buck/pull/1986/files#diff-849bfcb0b18649e5c25bc4e88e57ed40R168)

**Comment by kageiit** [comment]
@ttsugriy added integration tests

**Comment by ttsugriy** [comment]
thanks, @kageiit! I no longer work on Buck, so I cannot import your changes, but I'm sure @styurin would be able to help :)

**Pull request closed without merging**
