### PR TITLE
handle multiple linker warnings in agent detection

### PR DESCRIPTION
**Pull request by andrewzhaosc**
Under certain conditions pm can output more than one linker warning line

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @dcolascione and @cosmin1123 to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-1** [comment]
@andrewzhaosc updated the pull request - [view changes](https://github.com/facebook/buck/pull/886/files/ce161b00e4d8216e3935e63d1ad6b6df4efa8ce2..9aa4528d857b0b465e7efebe7d64275268221675)

**Comment by facebook-github-bot-9** [comment]
@andrewzhaosc updated the pull request - [view changes](https://github.com/facebook/buck/pull/886/files/9aa4528d857b0b465e7efebe7d64275268221675..6225fdb140e9ce382e53d2702252614cf184543b)

**Comment by Coneko** [comment]
Seems ok, will import once you sign the CLA.

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
