### PR TITLE
Replace "incorrect" types to make project generation work with xcodeproj 

### PR DESCRIPTION
**Pull request by fdiaz**
Buck currently outputs an XML for `project.pbxproj` where `runOnlyForDeploymentPostprocessing` and `dstSubfolderSpec` are treated as `integer`.

```
			<key>runOnlyForDeploymentPostprocessing</key>
			<integer>1</integer>
			<key>dstSubfolderSpec</key>
			<integer>16</integer>
```

When trying to open the `.xcodeproj` file with [xcodeproj](https://github.com/CocoaPods/Xcodeproj) we're getting:

> [Xcodeproj] Type checking error: got `Fixnum` for attribute: Attribute `dstSubfolderSpec` (type: `simple`, classes: `[String]`, owner class: `PBXCopyFilesBuildPhase`)

This [seems to be a bug](https://github.com/CocoaPods/Xcodeproj/issues/475) in xcodeproj itself.

To work around this, I'm forcing these 2 keys to have Strings as values instead of Int. After doing this, `xcodeproj` can succesfully open our project.

This was all already done in our [fork of buck here](https://github.com/airbnb/buck/pull/8)

---

I'm also including here @donholly commit in their fork that adds the same workaround for the same issue in PBXContainerItemProxy https://github.com/Clubroom/buck/commit/8fa5ae58c5df0e991d2f2e80830a73206c384bf3

### CODE REVIEW

**Comment by dfed** [comment]
Any chance of getting this reviewed?

**Comment by v-jizhang** [comment]
Hi @fdiaz, could you fix the test failures? Thanks
`FAIL    <100ms  1 Passed   0 Skipped   2 Failed   com.facebook.buck.apple.project_generator.PBXBuildPhasesTest`

**Comment by fdiaz** [comment]
@v-jizhang I couldn't find instructions in the repo to run the test suite. Can you provide instructions to validate locally before pushing the changes?

**Comment by v-jizhang** [comment]
@fdiaz, You can use the "buck test" to run tests locally.

- buck test //test/com/facebook/buck/...
This command runs all the tests. You usually don't want to run it because it takes a long time to finish.

- buck test //test/com/facebook/buck/apple/...
This command runs all the test in apple area and it is what you want to run for your changes. 

- buck test //test/com/facebook/buck/apple/xcode:xcode
This command runs an individual test suite.

**Comment by v-jizhang** [comment]
https://buck.build/command/test.html

**Comment by fdiaz** [comment]
@v-jizhang just pushed another commit with the test fixes, thanks for the help with running these locally!

**Comment by v-jizhang** [comment]
@fdiaz, your changes have been merged, thank you for your contributions.

**Pull request closed without merging**
