### PR TITLE
haskell: add GHC to travis

### PR DESCRIPTION
**Pull request by andrewjcg**
Summary:
So Haskell tests actually run.

### CODE REVIEW

**Comment by sdwilsh** [comment]
It doesn't look like this is passing travis.  Do we need to make changes to Buck?

**Comment by andrewjcg** [comment]
Looks like the default ghc is 7.4, which might be too old.  Trying again with 7.6.

**Comment by andrewjcg** [comment]
Used a PPA (https://launchpad.net/~hvr/+archive/ubuntu/ghc) which provides a new GHC (as per the pandoc example, https://github.com/jgm/pandoc/blob/master/.travis.yml, linked from https://docs.travis-ci.com/user/languages/haskell/).

**Comment by andrewjcg** [comment]
If the tests pass, I'll update again to use GHC-8.

**Comment by andrewjcg** [comment]
Ok, looks like the haskell tests run and pass now.

**Comment by styurin** [comment]
Looks like it's working, do you want to merge it?

**Pull request merged**
