### PR TITLE
Pex in-place packages, take 2

### PR DESCRIPTION
**Pull request by mikekap**
This time without the micro version (since CPython at least promises not to break ABI compat on micro upgrades). Is there any code you guys have that depends on the system python vs pyrun distinction? The ABI should be the same there, but that's the only change now.

### CODE REVIEW

**Comment by Coneko** [comment]
Wow that was fast, @andrewjcg was looking into reverting the revert with a fix, so I'll assign this to him.

**Comment by mikekap** [comment]
I'm in between jobs until next week, so I have a lot of free time...

**Comment by mikekap** [comment]
Ping

**Comment by mikekap** [comment]
Ping

**Comment by Coneko** [comment]
@facebook-github-bot shipit

**Comment by mikekap** [comment]
This PR is approaching 2.5 months now. Is there any chance of this getting committed? All it does is introduce pex tool flags & change the python version fetching implementation. I can probably rip out the latter too if that's the issue, though it's more correct since it distinguishes interpreter types (PyPy/Jython/CPython).

**Comment by sdwilsh** [comment]
Looking at the internal change, it looks like the diff failed to apply when @Coneko imported it.  It's possible rebasing would help, but it might also require more manual intervention which is why @Coneko hasn't landed it yet.

**Comment by Coneko** [comment]
This is landed internally. There's some issues with our git hooks that is preventing the commit to be published to open source, but we hope to solve it soon.

**Comment by Coneko** [comment]
Sorry it took so long, I kept getting pulled away by other stuff.

**Comment by mikekap** [comment]
No worries; I was more wondering whether there was something off with the change. Thanks for pushing it through 👍

**Pull request closed without merging**
