### PR TITLE
Improved Gradle-Android project's integration in Intellij

### PR DESCRIPTION
**Pull request by FrancisToth**
The following improvements have been made :
- Settings have been added to define default Java settings used across a project's modules. These settings are used to generate the file ".idea/misc.xml" required by Intellij 
```python
[java]
    # defines the java language level used across a project's different modules
    language_level=JDK_1_6

    # defines the JDK name used by the project in Intellij (depends on your environment)
    jdk_name=Android API 19 Platform 

    # defines the type of JDK used inside the project (eg. Python SDK, JavaSDK, Python SDK...)
    jdk_type=Android SDK
```

- Configuration parameters have also been added to improve Android-Gradle projects to Buck. This give more flexibility in the way a module's iml file is generated. By default, Buck considers that assets, the AndroidManifest and the resources are at the project's root. However, with Gradle, they're usually in : 
```[root]/src/main. ```

The following settings allow to tune these path and to set them according the project's file hierarchy :
```python
[project]

# defines each library's Manifest relative path (by default set to '/AndroidManifest.xml')
default_android_manifest_path = /src/main/AndroidManifest.xml

# defines each library's resource folder relative path (by default set to '/res')
default_android_resource_path = /src/main/res

# defines each library's assets folder relative path (by default set to '/assets')
default_android_assets_path = /src/main/assets
```

- Finally, some fixes have been done in order to improve prebuilt AAR's integration with Intellij. Formerly, generating the project file of a module having an AAR as a dependency could introduce duplicate entries inside the resulted iml file. Everything related to a prebuilt AAR is now stored in .idea/libraries/[library's name].xml : 
```xml
<component name="libraryTable">
  <library name="__third_party_viewpagerindicator">
    <CLASSES>
      <root url="jar://$PROJECT_DIR$/buck-out/bin/third-party/__uber_classes_[aarname]#aar_unzip__/classes.jar!/" />
      <root url="file://$PROJECT_DIR$/buck-out/bin/third-party/__unpack_[aarname]#aar_unzip__/res" />
      <root url="file://$PROJECT_DIR$/buck-out/bin/third-party/__unpack_[aarname]#aar_unzip__/assets" />
    </CLASSES>
    <JAVADOC />
    <SOURCES />
  </library>
</component>
  ```

### CODE REVIEW

**Comment by Coneko** [comment]
Sorry this slipped through the cracks. Are you still interested in merging this in? If so can you please merge from master?

**Comment by FrancisToth** [comment]
Hi ! I'm gonna make a clean rebase and ask for merging.

**Comment by Coneko** [comment]
Thanks, I've patched the PR locally and fixed some styling issues.

It would be nice if you could add an integration test. Have a look at the ones in `ProjectIntegrationTest` for examples.

Let me know if you have trouble figuring out how the test data is supposed to be laid out.

I will try to push out the style changes so you can merge them into the PR.

**Comment by FrancisToth** [comment]
I've just pushed everything and made some fixes. An integration test is still required, and I'll do that tomorrow. Regarding the build, do you have any idea why it is not passing ? All tests are green locally, and Travis does not specify any clear reason explaining why it has failed.

**Comment by Coneko** [comment]
I had to do some local changes to get everything to pass.
We run linters on CI, some of those failed.
You can run `ant lint` and `ant verify-javadoc` to run some of those locally.
I'll try to get my changes merged and put up a branch with both sets of changes.

Thanks for keeping your PR updated, much appreciated!

**Comment by FrancisToth** [comment]
Thank for those informations, next I'll check those aspects before pushing. Now the build is ok but unfortunately, one test is still failing : [ExternalJavacIntegrationTest](https://github.com/facebook/buck/blob/e8190a34ff10bdb55729a8a50669805f833f6a85/test/com/facebook/buck/java/ExternalJavacIntegrationTest.java) : 
<pre><code>FAILURE whenBuckdUsesExternalJavacThenClientEnvironmentUsed: java.io.IOException: Cannot run program "watchman": error=2, No such file or directory
java.lang.RuntimeException: java.io.IOException: Cannot run program "watchman": error=2, No such file or directory
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.facebook.buck.util.WatchmanWatcher$1.get(WatchmanWatcher.java:192)
	at com.facebook.buck.util.WatchmanWatcher$1.get(WatchmanWatcher.java:185)
	at com.facebook.buck.util.WatchmanWatcher.postEvents(WatchmanWatcher.java:207)
	at com.facebook.buck.cli.Main$Daemon.watchFileSystem(Main.java:284)
	at com.facebook.buck.cli.Main$Daemon.access$1000(Main.java:160)
	at com.facebook.buck.cli.Main.getParserFromDaemon(Main.java:781)
	at com.facebook.buck.cli.Main.executeCommand(Main.java:603)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:452)
	at com.facebook.buck.testutil.integration.ProjectWorkspace.runBuckCommandWithEnvironmentAndContext(ProjectWorkspace.java:315)
	at com.facebook.buck.testutil.integration.ProjectWorkspace.runBuckdCommand(ProjectWorkspace.java:248)
	at com.facebook.buck.testutil.integration.ProjectWorkspace.runBuckdCommand(ProjectWorkspace.java:242)
	at com.facebook.buck.java.ExternalJavacIntegrationTest.whenBuckdUsesExternalJavacThenClientEnvironmentUsed(ExternalJavacIntegrationTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.facebook.buck.junit.BuckBlockJUnit4ClassRunner$SameThreadFailOnTimeout$1.call(BuckBlockJUnit4ClassRunner.java:122)
	at com.facebook.buck.junit.BuckBlockJUnit4ClassRunner$SameThreadFailOnTimeout$1.call(BuckBlockJUnit4ClassRunner.java:118)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "watchman": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at com.facebook.buck.util.WatchmanWatcher$1.get(WatchmanWatcher.java:190)
	... 27 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 28 more
</code></pre>
 I've noticed this problem some days ago, and managed to fix it by installing a fresh version of watchman : 
<pre><code>$ git clone https://github.com/facebook/watchman.git
$ cd watchman
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install</code></pre>

**Comment by Coneko** [comment]
This has been merged internally and will go out in the next push!

Thanks again for your patience!

**Comment by FrancisToth** [comment]
No problem :) I'm happy to contribute !

**Pull request closed without merging**
