### PR TITLE
Package pathlib and pywatchman as PackagedResources.

### PR DESCRIPTION
**Pull request by shs96c**
This allows us to ship the PEX without having either `pathlib`
or `pywatchman` pre-installed requirement on a user's machine.

### CODE REVIEW

**Comment by shs96c** [comment]
I think that this fixes the problem seen here on the Selenium CI builds, which don't have pathlib available in their python installs: http://ci.seleniumhq.org:8080/job/Firefox%2038%20Linux%20Javascript%20Tests/2775/console

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @yiding, @yschimke and @dcolascione to be potential reviewers.

**Comment by sdwilsh** [comment]
cc @wez

**Comment by yschimke** [comment]
I notice the watchman target skips a native library for bser.  Do you expect this to have any noticeable performance impact?

https://github.com/facebook/buck/blob/master/third-party/py/pywatchman/BUCK

**Comment by yschimke** [comment]
LGTM.  But I don't have much experience with this code, generally looks sensible.

**Comment by shs96c** [comment]
I've not measured the performance delta, but the pywatchman python_library doesn't have the C code as a dep, so it's not used by anything that links against it anyway.

**Comment by Coneko** [comment]
```
TESTS FAILED: 2 FAILURES
Failed target: //test/com/facebook/buck/parser:parser
FAIL com.facebook.buck.parser.ParserTest
[Tue, 06 Sep 2016 08:18:10] Step "Testing with Buck" failed with: Summary (beta): 
FAILURE com.facebook.buck.parser.ParserTest resolveTargetSpecsPreservesOrder[2]: Unable to unpack pywatchman-archive.zip
[CONTEXT] java.lang.RuntimeException: Unable to unpack pywatchman-archive.zip
[CONTEXT] 	at com.facebook.buck.util.PackagedResource.unpack(PackagedResource.java:140)
[CONTEXT] 	at com.facebook.buck.util.PackagedResource.access$000(PackagedResource.java:44)
[CONTEXT] 	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:74)
[CONTEXT] 	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:71)
[CONTEXT] 	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131)
[CONTEXT] 	at com.facebook.buck.util.PackagedResource.get(PackagedResource.java:81)
[CONTEXT] 	at com.facebook.buck.json.BuckPythonProgram.newInstance(BuckPythonProgram.java:96)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.getPathToBuckPy(ProjectBuildFileParser.java:616)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.buildArgs(ProjectBuildFileParser.java:251)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.init(ProjectBuildFileParser.java:207)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.initIfNeeded(ProjectBuildFileParser.java:192)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesInternal(ProjectBuildFileParser.java:353)
[CONTEXT] 	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesAndMetaRules(ProjectBuildFileParser.java:342)
[CONTEXT] 	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:117)
[CONTEXT] 	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:107)
[CONTEXT] 	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
[CONTEXT] 	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
[CONTEXT] 	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
[CONTEXT] 	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
[CONTEXT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[CONTEXT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[CONTEXT] 	at java.lang.Thread.run(Thread.java:744)
FAILURE com.facebook.buck.parser.ParserTest resolveTargetSpecsDoesNotHangOnException[2]: 
[CONTEXT] Expected: (an instance of com.facebook.buck.json.BuildFileParseException and exception with message a string containing "Parse error for build file" and exception with message a string containing "bar/BUCK")
[CONTEXT]      but: an instance of com.facebook.buck.json.BuildFileParseException <java.lang.RuntimeException: Unable to unpack pywatchman-archive.zip> is a java.lang.RuntimeException
```

**Comment by Coneko** [comment]
This message has one more level:

```
FAILURE com.facebook.buck.parser.ParserTest resolveTargetSpecsPreservesOrder[2]: Unable to unpack pywatchman-archive.zip
java.lang.RuntimeException: Unable to unpack pywatchman-archive.zip
	at com.facebook.buck.util.PackagedResource.unpack(PackagedResource.java:140)
	at com.facebook.buck.util.PackagedResource.access$000(PackagedResource.java:44)
	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:74)
	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:71)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131)
	at com.facebook.buck.util.PackagedResource.get(PackagedResource.java:81)
	at com.facebook.buck.json.BuckPythonProgram.newInstance(BuckPythonProgram.java:96)
	at com.facebook.buck.json.ProjectBuildFileParser.getPathToBuckPy(ProjectBuildFileParser.java:616)
	at com.facebook.buck.json.ProjectBuildFileParser.buildArgs(ProjectBuildFileParser.java:251)
	at com.facebook.buck.json.ProjectBuildFileParser.init(ProjectBuildFileParser.java:207)
	at com.facebook.buck.json.ProjectBuildFileParser.initIfNeeded(ProjectBuildFileParser.java:192)
	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesInternal(ProjectBuildFileParser.java:353)
	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesAndMetaRules(ProjectBuildFileParser.java:342)
	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:117)
	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:107)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.nio.file.NoSuchFileException: /tmp/junit-temp-path545007687376792998/buck-out/res/com.facebook.buck.json.BuckPythonProgram/pywatchman/pywatchman/__init__.py
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:315)
	at com.facebook.buck.io.ProjectFilesystem.newUnbufferedFileOutputStream(ProjectFilesystem.java:832)
	at com.facebook.buck.io.ProjectFilesystem.newFileOutputStream(ProjectFilesystem.java:824)
	at com.facebook.buck.zip.Unzip.extractZipFile(Unzip.java:97)
	at com.facebook.buck.util.PackagedResource.unpack(PackagedResource.java:125)
	... 21 more
```

**Comment by Coneko** [comment]
And the other test fails because a different underlying issue:

```
FAILURE com.facebook.buck.parser.ParserTest resolveTargetSpecsDoesNotHangOnException[2]: 
Expected: (an instance of com.facebook.buck.json.BuildFileParseException and exception with message a string containing "Parse error for build file" and exception with message a string containing "bar/BUCK")
     but: an instance of com.facebook.buck.json.BuildFileParseException <java.lang.RuntimeException: Unable to unpack pywatchman-archive.zip> is a java.lang.RuntimeException
Stacktrace was: java.lang.RuntimeException: Unable to unpack pywatchman-archive.zip
	at com.facebook.buck.util.PackagedResource.unpack(PackagedResource.java:140)
	at com.facebook.buck.util.PackagedResource.access$000(PackagedResource.java:44)
	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:74)
	at com.facebook.buck.util.PackagedResource$1.get(PackagedResource.java:71)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131)
	at com.facebook.buck.util.PackagedResource.get(PackagedResource.java:81)
	at com.facebook.buck.json.BuckPythonProgram.newInstance(BuckPythonProgram.java:96)
	at com.facebook.buck.json.ProjectBuildFileParser.getPathToBuckPy(ProjectBuildFileParser.java:616)
	at com.facebook.buck.json.ProjectBuildFileParser.buildArgs(ProjectBuildFileParser.java:251)
	at com.facebook.buck.json.ProjectBuildFileParser.init(ProjectBuildFileParser.java:207)
	at com.facebook.buck.json.ProjectBuildFileParser.initIfNeeded(ProjectBuildFileParser.java:192)
	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesInternal(ProjectBuildFileParser.java:353)
	at com.facebook.buck.json.ProjectBuildFileParser.getAllRulesAndMetaRules(ProjectBuildFileParser.java:342)
	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:117)
	at com.facebook.buck.parser.ProjectBuildFileParserPool$1.apply(ProjectBuildFileParserPool.java:107)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/junit-temp-path604876482490844403/buck-out/res/com.facebook.buck.json.BuckPythonProgram/pywatchman
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1077)
	at com.facebook.buck.io.MoreFiles$3.postVisitDirectory(MoreFiles.java:193)
	at com.facebook.buck.io.MoreFiles$3.postVisitDirectory(MoreFiles.java:176)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:224)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2600)
	at java.nio.file.Files.walkFileTree(Files.java:2633)
	at com.facebook.buck.io.MoreFiles.deleteRecursivelyWithOptions(MoreFiles.java:201)
	at com.facebook.buck.io.MoreFiles.deleteRecursivelyIfExists(MoreFiles.java:104)
	at com.facebook.buck.io.ProjectFilesystem.deleteRecursivelyIfExists(ProjectFilesystem.java:740)
	at com.facebook.buck.util.PackagedResource.unpack(PackagedResource.java:116)
	... 21 more
```

**Comment by wez** [comment]
(cleaning up my PR mentions and this doesn't seem like it is moving, so closing it!)

**Pull request closed without merging**
