### PR TITLE
[WIP] Add option for swift version to use in buckconfig

### PR DESCRIPTION
**Pull request by nguyentruongtho**
Not only adding option to specify swift version, I also tried to decouple objective C and swift, so that we could benefit from making buck to work with swift on non-Apple OS (linux, windows...).

Should resolve the issue mentioned here https://github.com/facebook/buck/issues/423#issuecomment-248777961

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @jernejstrasner, @ryu2 and @Coneko to be potential reviewers.

**Comment by facebook-github-bot-9** [comment]
@nguyentruongtho updated the pull request - [view changes](https://github.com/facebook/buck/pull/893/files/cf9618ce194258cd4ab0ed4e7b62ae8fe6e9143e..f16d7a225f341a6971a0094f7632900ba63dddf3)

**Comment by Coneko** [comment]
Seems good, can you split it in two separate PRs: one for adding `SwiftPlatform` and related refactoring, and one for adding the version config.

**Comment by nguyentruongtho** [comment]
Closed in favor of using 2 smaller PRs https://github.com/facebook/buck/issues/896 & https://github.com/facebook/buck/pull/899.

**Pull request closed without merging**
