### PR TITLE
Stop spamming the action graph with GWT modules.

### PR DESCRIPTION
**Pull request by shs96c**
There's no need to do this any more. We should stop.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @bolinfest, @keelerh and @aiked to be potential reviewers.

**Comment by shs96c** [comment]
I'm doing some clean up of how the selenium fork handles maven, javadoc, and source jars, and this came loose. Sits in a nice diff on its own, and tidies up the main tree.

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3757204) to review internal test results.

**Comment by shs96c** [comment]
I think it's just autodeps clashing.

**Pull request closed without merging**
