### PR TITLE
Get devices function

### PR DESCRIPTION
**Pull request by tgummerer**
This pull request depends on the Refactor AdbHelper pull request I sent earlier (I was under the impression that one pull request per commit is preferred).

@sdwilsh I saw that you commented, that you'd like me to add a test for this, but I don't know how to test this, as the return value depends on the devices that are connected to the machine where the tests are run, and I didn't find a way to get the AndroidDebugBridge to return a predefined list of devices, as all it's constructors are private.

### CODE REVIEW

**Comment by sdwilsh** [comment]
Hmm, this ended up pulling in both of your changes.

**Comment by tgummerer** [comment]
Yeah, sorry I didn't notice.  I tried, but GitHub doesn't seem to let me just add one commit to the pull request, as the second one depends on the first one.  I could make it a separate commit, not depending on the first one, but that will result in a merge conflict, so I guess it's still simpler for you this way?

**Comment by sdwilsh** [comment]
Oh GitHub.  I'll merge your change shortly, so it should be easy to 
rebase and make that issue go away.

**Comment by tgummerer** [comment]
Thanks, I saw you merged the other pull request now, so I updated this one to just include the right commit.

**Comment by sdwilsh** [comment]
Thanks for pulling this out!

**Pull request closed without merging**
