### PR TITLE
Added maven flavor to scala_library

### PR DESCRIPTION
**Pull request by romanoid**
This allows publishing scala libraries via `buck publish`

### CODE REVIEW

**Comment by styurin** [comment]
Can you add tests, please?

**Comment by romanoid** [comment]
will add some tests early next week, please not import before that .

**Comment by romanoid** [comment]
I assume commits will be squashed on land automatically, please let me know if it is cleaner to squash them on my side.

**Comment by styurin** [comment]
Looks like build is failing

**Comment by romanoid** [comment]
I've managed to failed PMD: 
```
pmd:
      [pmd] /home/travis/build/facebook/buck/test/com/facebook/buck/cli/PublishCommandIntegrationTest.java:198:	Unnecessary use of fully qualified name 'Assert.assertTrue' due to existing static import 'org.junit.Assert.assertTrue'
```

Uploaded new revision with the issue fixed.

**Pull request closed without merging**
