### PR TITLE
Improvements to TestNG test runner

### PR DESCRIPTION
**Pull request by jiangty-addepar**
(This PR is on top of https://github.com/facebook/buck/pull/1653, so ignore the first commit for now.)

This is a collection of TestNG test improvements from our fork of Buck. Changes include:

- `Minor fixes to testng runner.`
    - Mark skipped tests as failed
    - No hard time limit per test suite
- `Respect ClassName and MethodName filters in TestNG runner.`
    - Make ClassName / MethodName filters work with TestNG runner
    - Remove TestNGWrapper
    - Remove "TmpSuite" xml suite
- `TestNG results now show method parameters.`
    - Show method parameters in TestNG test results (for example, for tests that use DataProviders)
- `Support Stdout and Exception Details when Test Setup Fails`
    - Fail test and print exceptions/stdout when test setup fails
    - Record all test failures in JUnit test report, including those from test setup

The remaining changes are to tests. I did some refactoring to use the `buck` cell (reducing jar duplication) for an existing test as well.

Test plan: `buck test`; added a number of integration tests.

### CODE REVIEW

**Comment by jiangty-addepar** [comment]
```Build failed: Failed to compile: No space left on device
    When running <javac_jar>.```

:( @ttsugriy

**Comment by jiangty-addepar** [comment]
Also, should I split this into multiple PRs?

**Comment by ttsugriy** [comment]
@jiangty-addepar, in general whenever possible please try to send independent chunks of work in separate PRs. As for no space left, I believe Travis CI has a 20GB limit for hard drive, so we'll have to come up with some way to reduce the number of things we install as well as consider sharing our tests even more :(

**Comment by jiangty-addepar** [comment]
Ok, I replaced this with #1662 #1663 #1664 #1665 .

**Pull request closed without merging**
