### PR TITLE
Fix travis-ci build.

### PR DESCRIPTION
**Pull request by brettwooldridge**
Ignore this pull request, just poking at travis to see if I can make it pass.

### CODE REVIEW

**Comment by Coneko** [comment]
Travis is still red after the latest update, I see some timeouts still happening.

**Comment by brettwooldridge** [comment]
@Coneko I think the real solution is to break up some of the Android unit tests into multiple files.

**Comment by Coneko** [comment]
Latest run's failures don't seem to be any of the usual ones, and might in fact be a legit failure that was never noticed because Travis was always red anyway.

Importing.

**Comment by brettwooldridge** [comment]
@Coneko Woohooo! Only one failure ``TESTS FAILED: 1 FAILURE``, in the ``go`` tests.

**Pull request closed without merging**
