### PR TITLE
Correct example to match the docs

### PR DESCRIPTION
**Pull request by Tpbrown**
Happened to notice the example was slightly off from the docs and wouldn't work.

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by sdwilsh** [comment]
This looks good.  We can import it once the CLA is signed :)

**Comment by Tpbrown** [comment]
@sdwilsh CLA signed, but I think the bot didn't update the label.

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by ryu2** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1520610964914381/int_phab) to review.

**Pull request closed without merging**
