### PR TITLE
targetSdkVersion mismatch should be only warning, don't fail building process

### PR DESCRIPTION
**Pull request by Piasy**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @styurin to be a potential reviewer.

**Comment by Piasy** [comment]
@styurin Could this pr be merged?

**Comment by Coneko** [comment]
cc @marcinkosiba, @michath 

I think we didn't want to modify the manifest merger since it comes from upstream, but I could be wrong.

**Comment by Piasy** [comment]
@Coneko 

> since it comes from upstream

I don't understand what is the upstream means.

Gradle build could handle this problem automatically. Hope BUCK could work well on this too.

**Comment by styurin** [comment]
@Piasy upstream means AOSP: https://android.googlesource.com/platform/sdk/+/a35f8af/manifmerger/src/com/android/manifmerger/ManifestMerger.java

We don't want to introduce fixes that change logic in code that is taken from other libraries. The main concern here is maintenance cost of such changes in cases when we need to update our copy of this library with a new version from upstream.

**Comment by Piasy** [comment]
Got it. But android gradle plugin works well in this case, I'll figure out how does it works.

**Comment by styurin** [comment]
Thanks, let us know what you find, we may only need to update ManifestMerger from upstream.

**Pull request closed without merging**
