### PR TITLE
Fix RES_FOLDERS_RELATIVE_PATH to be actually relative

### PR DESCRIPTION
**Pull request by kageiit**
This changes the behavior of buck project to correctly set the `RES_FOLDERS_RELATIVE_PATH` value to be relative to the module. The android intellij plugin expects a proper relative path and does not work when macros like `$MODULE_DIR` etc. are prepended to the path.

This change is required to support Android Layout Preview in buck project and intellij.

### CODE REVIEW

**Comment by christolliday** [comment]
Can you rebase and make this build? There's a method missing.

**Comment by kageiit** [comment]
> Can you rebase and make this build? There's a method missing.

Will do!

**Comment by kageiit** [comment]
@christolliday Fixed the missing method and rebased

**Comment by kageiit** [comment]
@christolliday Fixed the tests

**Pull request closed without merging**
