### PR TITLE
Make kotlin_home buck config support specifying source path.

### PR DESCRIPTION
**Pull request by raviagarwal7**
- Support specifying a source path for `kotlin_home` buck config
- Simplified and cleaned up logic to look up kotlin home.
- Updated Docs

Resolves https://github.com/facebook/buck/issues/2121

Dependent PR’s:
https://github.com/facebook/buck/pull/2131
https://github.com/facebook/buck/pull/2130

### CODE REVIEW

**Comment by raviagarwal7** [comment]
this is now ready for review.

cc: @styurin, @thalescm, @kageiit

**Comment by styurin** [comment]
Is that possible to split this PR?

**Comment by styurin** [comment]
Also, Travis CI builds are failing.

**Comment by raviagarwal7** [comment]
sure, let me break this PR into smaller ones.

**Comment by raviagarwal7** [comment]
will rebase once https://github.com/facebook/buck/pull/2131 gets merged.

**Comment by kageiit** [comment]
cc @styurin this is rebased and ci is green. Can we please import? :)

**Comment by raviagarwal7** [comment]
@styurin, was the import successful?

**Pull request closed without merging**
