### PR TITLE
Add support for sources and javadoc to AndroidPrebuiltAar

### LINKED ISSUE #334: android_prebuilt_aar: Add support for source JAR
For example the Android Support Library ships as an .aar and a separate -sources.jar.

When depending on the .aar and generating an IntelliJ/Android studio project using 'buck project', it should be possible to navigate to sources.

Context: http://stackoverflow.com/questions/30533769/source-jar-with-bucks-android-prebuilt-aar

### PR DESCRIPTION
**Pull request by kageiit**
Fixes #334

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @Coneko, @tonycosentini and @mikekap to be potential reviewers.

**Comment by kageiit** [comment]
cc @marcinkosiba

**Comment by marcinkosiba** [comment]
please add a test case to `IjModuleFactoryTest` for this.

**Comment by facebook-github-bot-5** [comment]
@kageiit updated the pull request - [view changes](https://github.com/facebook/buck/pull/833/files/f3482139abb02dccf524f6cd0a44090420e43824..00778edc3fe8667b7ef84a9faee7169c4a3c1457)

**Comment by kageiit** [comment]
@marcinkosiba added tests

**Comment by facebook-github-bot-0** [comment]
@kageiit updated the pull request - [view changes](https://github.com/facebook/buck/pull/833/files/00778edc3fe8667b7ef84a9faee7169c4a3c1457..002b7500aefd05e2976e9e4bef4dd14e37fe0b4c)

**Comment by kageiit** [comment]
@marcinkosiba the travis failure seems to be due to integration tests which this PR does not touch

**Comment by kageiit** [comment]
@sdwilsh Can you please help merge this?

**Comment by sdwilsh** [comment]
I think this is okay, but I haven't worked on Buck code in about six months, so I'm not comfortable accepting this.  With that said, it might be good to get an integration test to use this in a BUCK file too, and the docs for the rule need to be updated as well.

Maybe @marcinkosiba can look at it once you do that.

**Comment by facebook-github-bot-5** [comment]
@kageiit updated the pull request - [view changes](https://github.com/facebook/buck/pull/833/files/002b7500aefd05e2976e9e4bef4dd14e37fe0b4c..e653e247bee17abe0a74410b06b83d1c56783f61)

**Comment by kageiit** [comment]
@sdwilsh the unit test is pretty much an integration test by itself, as the code path is fairly trivial.

I updated the documentation as suggested. Will wait for @marcinkosiba to take a look

Thanks!

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by kageiit** [comment]
@marcinkosiba seems like this is not closed still

**Comment by marcinkosiba** [comment]
@kageiit looks like facebook-github-bot doesn't like me, not sure why. I'll look into it.

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3925060).

**Comment by marcinkosiba** [comment]
@kageiit - travis correctly failed on line length limits. I'll fix it up for you this time, but please pay attention to the travis build in the future.

**Comment by kageiit** [comment]
> @kageiit - travis correctly failed on line length limits. I'll fix it up for you this time, but please pay attention to the travis build in the future.

Ah sorry about that. The log was huge, I did not see it correctly. Thanks for fixing the line lengths

**Pull request closed without merging**
