### PR TITLE
Refactor exopackage installer

### PR DESCRIPTION
**Pull request by tgummerer**
This is another pull request that will mainly benefit the work I'm currently doing for the android_instrumentation_test rule.  Thought I'd get this out early, as it makes sense on it's own, and the end game will be simpler without this included.

### CODE REVIEW

**Comment by sdwilsh** [comment]
Okay, I got your first commit in.  I had to fix up some lint and java doc issues.  Can you rebase this so I can get the second one in too?

**Comment by tgummerer** [comment]
Sorry about that.  Is there any way to catch those issues automatically? I rebased the second commit now.

**Comment by sdwilsh** [comment]
If you run `ant lint verify-javadoc`, you should be good.

**Comment by tgummerer** [comment]
Thanks, will do for my future commits.

**Pull request closed without merging**
