### PR TITLE
Fix swift linking when swift version is specified

### PR DESCRIPTION
**Pull request by nguyentruongtho**
Given swift version is specified in .buckconfig, which is different to the default swift, https://github.com/facebook/buck/pull/899 works for standalone swift target, but doesn't cover the case when there are multiple swift targets depend on each other, which will fail at linking time.

This PR will fix that problem.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @Coneko, @jernejstrasner and @yiding to be potential reviewers.

**Comment by dinhviethoa** [comment]
@ryu2 Could you take a look at this one?

**Comment by nguyentruongtho** [comment]
image

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3927225).

**Pull request closed without merging**
