### PR TITLE
Remove the AbstractDescriptionArg

### PR DESCRIPTION
**Pull request by shs96c**
There's no need to inherit from a base class for constructor
args. Doing so prevents Buck users from using domain classes
as an arg (which is, admittedly, a little odd but still nice
to have as a possibility)

Instead, add the parameter available on all args to the same
place as every other global parameter.

### CODE REVIEW

**Comment by shs96c** [comment]
As an aside, when I wrote the original coercer and reflective magic, I very deliberately chose to avoid forcing people to inherit from a buck class for their parameters. Generally they fall into "everything has it", in which case it should just be handled transparently, or "specific to a rule, but perhaps incredibly common", in which case having it be on the arg is a Bad Idea.

**Comment by yiding** [comment]
Why did we make AbstractDescriptionArg... all for `licenses`? that seems a bit silly.

I'd like this to eventually do something like immutables, so you can include a bunch of interfaces and then the actual record class gets codegenned from all the interface methods.

**Comment by sdwilsh** [comment]
This was the solution @marcinkosiba and I came up with for licenses because putting it in `BuckPyFunction` is rather non-discoverable unless you happen to know Buck internals really well.

**Comment by Coneko** [comment]
I'm confused, how are you supposed to access the licenses with this change? They're not a field on target node like visibility and they're not a field on the constructor arg like before this change.

I guess it's @sdwilsh's bad for not adding a test, but `buck query "labels('licenses', deps('buck'))"` should return the list of licenses used in Buck.

**Comment by shs96c** [comment]
You do know the buck internals really well.

**Comment by shs96c** [comment]
Add the test and I'll make sure it passes. Probably should end up as a field on the targetnode.

**Comment by sdwilsh** [comment]
> You do know the buck internals really well.

I thought I did, but trying to add `licenses` proved that to not be totally true!

**Comment by marcinkosiba** [comment]
Args being concrete classes with fields (rather than following the immutables abstract method pattern) and Java not allowing fields on interfaces (or mixins) make this hard to express in the type system. 
I'd love be able to say:
```
interface CanHaveLicense {
  Optional<ImmutableSet<String>> getLicenses()  
}

class Arg implements CanHaveLicense {
}
```

(so essentially same thing as @yiding said above).
Making this stuff magical in the parser is a bit gross, though we don't really have enough of these special magic things to make a strong case for putting in the work to do the immutables-like approach.

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
