### PR TITLE
Add an option to run tests only if they are cached failed

### PR DESCRIPTION
**Pull request by mikekap**
Useful for retrying tests.

### CODE REVIEW

**Comment by kageiit** [comment]
Is the reason for this to retry flaky tests?

**Comment by mikekap** [comment]
Exactly that.

**Comment by kageiit** [comment]
What if a flaky test passed on the first run? There would never be a way to detect a real failure in that case right?

**Comment by mikekap** [comment]
Yes. This does not attempt to fix the flaky test problem generally - that problem already exists with Buck test result caching. What this attempts to do is give the user the chance to re run failing tests without rerunning the whole test suite. It's particularly useful in speeding up flaky CI when there are a lot of tests and only one fails.

**Comment by kageiit** [comment]
So it only reruns the failing tests in a whole set of tests defined by a test rule?

That seems like a good option to have in general as well

**Comment by mikekap** [comment]
It doesn't do that unfortunately. This re-runs the entire test targets that failed. Buck only has test suite unrolling for JVM based tests and that's only for UI. We could in theory generate the proper filter to re-run only the failed test cases here. That might be for another time though.

**Comment by kageiit** [comment]
Got it. so it only preserves results cache if all tests in the target passed. But would definitely be good to have a filter to run the failed tests from previous run without running every other test as well

**Comment by mikekap** [comment]
@yiding @Coneko ping

**Comment by marcinkosiba** [comment]
@mikekap - could you please update the docs to mention this new option?

**Comment by mikekap** [comment]
@marcinkosiba ping

**Pull request closed without merging**
