### PR TITLE
updated brainium on showcase.soy

### PR DESCRIPTION
**Pull request by darkforestzero**
- using latest icons hosted on google photos get SSL
- added solitaire and wordsearch

### CODE REVIEW

**Comment by darkforestzero** [comment]
@sdwilsh This should address the issues we discussed in your pull request (SSL images and missing apps)

**Comment by darkforestzero** [comment]
ping @sdwilsh .  Doesn't look like the travis failures have to do with my changes

**Comment by darkforestzero** [comment]
@sdwilsh ping

**Comment by styurin** [comment]
@darkforestzero is it still valid? Could you rebase, please?

**Pull request closed without merging**
