### PR TITLE
Build source jars without first compiling anything

### PR DESCRIPTION
**Pull request by shs96c**
We also make an effort to parse java sources so that we
can now include files that are generated as part of the
build. Wooo.

### CODE REVIEW

**Comment by shs96c** [comment]
I note with interest that `autodeps` had plenty of unused dependencies. Perhaps an intern could be "encouraged" to clean those up through the project?

**Comment by Coneko** [comment]
CI fails.

**Comment by shs96c** [comment]
Investigated failures. The `go` and `util` tests seem unrelated to this diff. Fixed the other one.

**Comment by Coneko** [comment]
Still failing. If you rebase on master the go test will be fixed.

**Comment by Coneko** [comment]
Still failing.

**Comment by shs96c** [comment]
Guess it's safe to ignore Appveyor since it can't even check out the build.

**Comment by Coneko** [comment]
Appveyor should be green on master, but yeah the failure doesn't seem related.

This one on the other hand:

```
Failed target: //test/com/facebook/buck/maven:maven
FAIL com.facebook.buck.maven.PublisherTest
```

**Comment by styurin** [comment]
Some things have probably changed since this PR was created. Do we still need it?

**Comment by shs96c** [comment]
Yes, we do. Building all the code to just create a source jar is excessive.

**Pull request closed without merging**
