### PR TITLE
don't bundle apps except in watch apps

### PR DESCRIPTION
**Pull request by rmaz**
Fix for apple bundle dependency bundling. It is only valid to bundle apps when they are watch apps. This prevents the bundling of apps inside test bundles that have test hosts.

### CODE REVIEW

**Comment by rmaz** [comment]
Side note: probably time to remove watch os1 support, I don't think anyones going to be building any of those any time soon.

**Comment by rmaz** [comment]
any more needed on this one, or good to go?

**Comment by rmaz** [comment]
@williamtwilson another month another gentle ping, let me know if there are any issues with this one

**Comment by v-jizhang** [comment]
Sorry we never got back to this! Thank you for your contributions. If you are still interested in merging your fix, please rebase and update this PR and we promise to look at it in a timely manner. Thank you (and sorry) again.

**Comment by v-jizhang** [comment]
Close it because there is no update for 8 months

**Pull request closed without merging**
