### PR TITLE
Add resources to `go_test`

### PR DESCRIPTION
**Pull request by mikekap**
This lets you depend on test data for the test.

### CODE REVIEW

**Comment by mikekap** [comment]
Ping

**Comment by beefon** [comment]
I've noticed `go_binary` does not have resources. Do you need them for tests only? Should you have "traditional" approach for this instead, like creating `go_resources()` and making `go_binary`/`go_library`/`go_test` possible to depend `go_resource`? Does it make any sense to have that?

**Comment by mikekap** [comment]
Go doesn't really have any support for resources itself - i.e. resources for tests are just files in the working directory. You can't really have a relocatable go executable with resources unless you embed them in the binary via something like https://github.com/jteeuwen/go-bindata.

**Comment by beefon** [comment]
ok then. I wonder what happened with builds though. Can you please rebase and retrigger CI?

**Comment by mikekap** [comment]
Travis is busted due to `ia32-libs` not working: https://github.com/travis-ci/travis-ci/issues/5707; windows is busted because some new code made it in that doesn't work on windows & some things time out on appveyor.

**Comment by beefon** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
