### PR TITLE
Add Google Analytics to the Buck website

### PR DESCRIPTION
**Pull request by lacker**
it's under the "Facebook Open Source Sites" GA org

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
By analyzing the blame information on this pull request, we identified @andrewjcg, @ryu2 and @LegNeato to be potential reviewers.

**Comment by sdwilsh** [comment]
This basically reverts 91cab95a67ed695bc8d554c2585c2ab022d1f06e, but uses the Facebook Open Source account instead of @bolinfest's own account.

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3744054) to review internal test results.

**Comment by Coneko** [comment]
Curly braces need to be escape in soy. Put up a fix.

**Comment by lacker** [comment]
Sorry! I think https://github.com/facebook/buck/pull/849 should fix it

**Comment by Coneko** [comment]
Oh sorry, actually I meant I had put up a fix, not that should have have put one up, but I'll import yours.

**Pull request closed without merging**
