### PR TITLE
Don't add SDKROOT to framework search paths

### PR DESCRIPTION
**Pull request by robbertvanginkel**
Not all of Apple's system frameworks have correct modular headers.
Adding the `$SDKROOT` in a `-F` flag triggers an attempt of clang to 
create a module for these, which gives unexpected errors.

Omitting the `$SDKROOT` is not an issue when the `-sdk` flag is passed to
`clang`/`swiftc`. When generating a new project in Xcode, it does not
include the `$SDKROOT` variable in `FRAMEWORK_SEARCH_PATHS` by
default.

Related radars:
- http://openradar.appspot.com/33774557
- http://openradar.appspot.com/33795982

### CODE REVIEW

**Comment by yiding** [comment]
There's some legit test failures in `com.facebook.buck.apple.CompilationDatabaseIntegrationTest`

**Comment by robbertvanginkel** [comment]
I must have missed that test. Pushed a fix.

**Comment by yiding** [comment]
There's some failures that you can see in the "travis ant" build. namely ant pmd and google java format stuff. I tried to just fix it internally but the tool keeps overwriting my changes.

**Comment by robbertvanginkel** [comment]
I ran the google-java-formatter and the pmd. I got rid of one pmd error, but I cant seem to fix:
```
pmd:
      [pmd] /Users/robbertvanginkel/buck/src/com/facebook/buck/cxx/CxxLibraryDescription.java	-	Error while parsing /Users/robbertvanginkel/buck/src/com/facebook/buck/cxx/CxxLibraryDescription.java
```
That error doesn't seem to fail ant though.

**Comment by yiding** [comment]
Yeah, the PMD parser has a bit of trouble with some java 8 stuff.

**Pull request closed without merging**
