### PR TITLE
Handle resource dependencies of static prebuilt frameworks

### PR DESCRIPTION
**Pull request by rmaz**
Make sure transitive dependencies of static frameworks are correctly bundled in containing bundles.

### CODE REVIEW

**Comment by rmaz** [comment]
@williamtwilson any concerns with this one, or good to go?

**Comment by thiagocruz-luizalabs** [comment]
Hello, this fix is really important to generate the xcode project correctly.
Currently, using the `prebuilt_apple_framework` with `preferred_linkage = 'static'` is including the framework inside the project's embedded binaries, which breaks the app.
Is it possible to merge it if there isn't any concerns?

**Comment by shepting** [comment]
We would love to see this merged as well.

**Comment by neacao** [comment]
Seem likes this PR is not merged yet

**Comment by v-jizhang** [comment]
Thank you for your contribution @rmaz . Could you rebase to master and let's get this PR reviewed.

**Comment by rmaz** [comment]
I'm not going to be able to spend time on this for the forseeable, if anyone wants to take this on please go ahead.

**Comment by codetucao** [comment]
@rmaz is there any risky that you aimed to ?

**Comment by Unknoob** [comment]
I've reopened this PR here with the rebase: https://github.com/facebook/buck/pull/2490

**Pull request closed without merging**
