### PR TITLE
Adding support for uppercase ide type

### PR DESCRIPTION
**Pull request by naveenOnarayanan**
With this https://github.com/facebook/buck/commit/fb9dae6d8c66ec5c23e7bea25d170335912a646b we lost the ability for ide type to be case insensitive when running **buck project**

This diff allows us to both define case insensitive IDE type in both the **.buckconfig** as CLI through the **--ide** flag.

### CODE REVIEW

**Comment by styurin** [comment]
It looks fine, but I'm just curios, is that something that blocks you in some way?

**Comment by naveenOnarayanan** [comment]
> It looks fine, but I'm just curios, is that something that blocks you in some way?

Hey Tyurin, unfortunately we utilized the uppercase approach in our internal plugins when interacting with BUCK and have been passing in **INTELLIJ** whenever we run buck project. Due to the fact that plugin rollouts are slow, we needed to have backwards compatibility support.

**Comment by styurin** [comment]
Could you re-format the source code? You can find instructions here: https://github.com/facebook/buck/blob/master/CONTRIBUTING.md#code-style

**Comment by naveenOnarayanan** [comment]
Reformatted the code using `google-java-format 1.6`

**Pull request closed without merging**
