### PR TITLE
Review addition of new package for intellij plugin

### PR DESCRIPTION
**Pull request by dakkad**
This is a simple pull request to check that everything ties up correctly.

### CODE REVIEW

**Comment by dakkad** [comment]
Hi,

I have registered for the Facebook contributor licencing agreement at https://code.facebook.com/cla

Thanks,

**Comment by dakkad** [comment]
Please IM me when this starts...

**Comment by Coneko** [comment]
What do you mean?

We have a plugin checked in in the meantime: https://github.com/facebook/buck/tree/master/src/com/facebook/buck/intellij/plugin

**Comment by dakkad** [comment]
GH bot added a review needed label, I meant let me know when that starts.

**Pull request closed without merging**
