### PR TITLE
Add support for custom compiler class names

### LINKED ISSUE #1019: Add support for custom compiler class names
Currently, the jar backed javac hardcodes `com.sun.tools.javac.api.JavacTool` as the implementation of `JavaCompiler`

https://github.com/facebook/buck/blob/8e3c38fcf5403808aa0529afe16b8e9978c9b427/src/com/facebook/buck/jvm/java/AbstractJavacOptions.java#L149

Proposal is to open that up with a `compiler_class_name` option that can work with `javac_jar` option.

This lets us integrate alternative compilers like Google's Error prone (https://github.com/google/error-prone) into the build process

### PR DESCRIPTION
**Pull request by kageiit**
Fixes #1019

### CODE REVIEW

**Comment by kageiit** [comment]
Happy to add tests, if I can be pointed to where to add them

**Comment by Coneko** [comment]
`JavacOptionsTest`, there's already some that test what is returned by `getJavac` there.

**Comment by Coneko** [comment]
In general if a certain functionality is completely enclosed in a class the test for it should go in the corresponding test suite, you can always create a new one if one doesn't exist.

**Comment by kageiit** [comment]
Added tests and docs

**Comment by Coneko** [comment]
Changes look good, but extract the copy pasta in the soy docs into a common template and call it.

**Comment by kageiit** [comment]
@Coneko fixed the templates. Also tested locally by running `./docs/soy2html.sh` and checking the output docs

Please take a look. Thanks

**Comment by zhihuawensc** [comment]
Is there a concrete example about how to use it with Google's Error prone compiler?

I am also interested in about how to use it with aspectj compiler?
The format used by Hugo at https://github.com/JakeWharton/hugo/blob/master/hugo-runtime/build.gradle is like below in gradle

android.libraryVariants.all { variant ->
  JavaCompile javaCompile = variant.javaCompile
  javaCompile.doLast {
    String[] args = [
        "-showWeaveInfo",
        "-1.5",
        "-inpath", javaCompile.destinationDir.toString(),
        "-aspectpath", javaCompile.classpath.asPath,
        "-d", javaCompile.destinationDir.toString(),
        "-classpath", javaCompile.classpath.asPath,
        "-bootclasspath", android.bootClasspath.join(File.pathSeparator)
    ]

    MessageHandler handler = new MessageHandler(true);
    new Main().run(args, handler)

    def log = project.logger
    for (IMessage message : handler.getMessages(null, true)) {
      switch (message.getKind()) {
        case IMessage.ABORT:
        case IMessage.ERROR:
        case IMessage.FAIL:
          log.error message.message, message.thrown
          break;
        case IMessage.WARNING:
        case IMessage.INFO:
          log.info message.message, message.thrown
          break;
        case IMessage.DEBUG:
          log.debug message.message, message.thrown
          break;
      }
    }
  }
}

**Comment by kageiit** [comment]
@zhihuawensc I think for your purpose, it should be done as a `postprocess_classes_command` instead. Similar to how retrolambda works right now in okbuck

**Pull request closed without merging**
