### PR TITLE
Allow prebuilt_jar to work with directories as the binary jar.

### PR DESCRIPTION
**Pull request by mikekap**
Turns out most of the code actually supports this use case already.

Separately, why do both `prebuilt_jar` & `export_file` copy the contents? Should they be using `HasRuntimeDeps` instead?

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @jkeljo, @andrewjcg and @Coneko to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@mikekap updated the pull request.

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by marcinkosiba** [comment]
> Separately, why do both prebuilt_jar & export_file copy the contents? Should they be using HasRuntimeDeps instead?

I believe they were written before we had runtime deps

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/522582897866656/int_phab) to review.

**Comment by marcinkosiba** [comment]
Seems like there is a legitimate test failure here

Failed target: //test/com/facebook/buck/jvm/java:java
FAIL com.facebook.buck.jvm.java.PrebuiltJarIntegrationTest
[Tue, 17 May 2016 06:39:23 -0700] Step "Testing with Buck" failed with: Summary (beta): 
FAILURE com.facebook.buck.jvm.java.PrebuiltJarIntegrationTest testPrebuiltJarGenruleDirectory: Expected exit code 0 but was 1.
[CONTEXT] java.lang.AssertionError: Expected exit code 0 but was 1.
[CONTEXT] 	at org.junit.Assert.fail(Assert.java:88)
[CONTEXT] 	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertExitCode(ProjectWorkspace.java:643)
[CONTEXT] 	at com.facebook.buck.testutil.integration.ProjectWorkspace$ProcessResult.assertSuccess(ProjectWorkspace.java:604)
[CONTEXT] 	at com.facebook.buck.jvm.java.PrebuiltJarIntegrationTest.testPrebuiltJarGenruleDirectory(PrebuiltJarIntegrationTest.java:101)
[CONTEXT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[CONTEXT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[CONTEXT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[CONTEXT] 	at java.lang.reflect.Method.invoke(Method.java:606)
[CONTEXT] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[CONTEXT] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[CONTEXT] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[CONTEXT] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[CONTEXT] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[CONTEXT] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[CONTEXT] 	at com.facebook.buck.testrunner.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:45)
[CONTEXT] 	at com.facebook.buck.testrunner.SameThreadFailOnTimeout$1.call(SameThreadFailOnTimeout.java:41)
[CONTEXT] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[CONTEXT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[CONTEXT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[CONTEXT] 	at java.lang.Thread.run(Thread.java:744)

[2016-05-17 06:37:03.992][warn ][tid:5186][com.facebook.buck.event.listener.LoggingBuildListener] BUILD FAILED: //:genjardir failed with exit code 255:
genrule
stderr: Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.6/zipfile.py", line 1409, in <module>
    main()
  File "/usr/lib64/python2.6/zipfile.py", line 1383, in main
    fp = open(tgt, 'wb')
IOError: [Errno 21] Is a directory: u'/tmp/buck-f7e8b563-8ae4-4512-b262-c8c24da606ae/test/com/facebook/buck/jvm/java/__java_test_java_tmp__/junit4013778068020185065/buck-out/gen/genjardir/junit2/META-INF/'

**Comment by mikekap** [comment]
https://bugs.python.org/issue4710 :'( Updated with a custom unzipper.

**Comment by facebook-github-bot-6** [comment]
@mikekap updated the pull request.

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by mikekap** [comment]
ping

**Comment by marcinkosiba** [comment]
sorry for the delay. Turns we use python 2.7 on travis when running tests but our internal CI uses 2.6, so this was choking on land. Fixed the test, should be in soon

**Comment by mikekap** [comment]
Ah no problem. Feel free to lmk about those cases - I'm more than happy to fix them myself (I just don't normally test on 2.6 because that requires finding a docker container).

**Comment by marcinkosiba** [comment]
I'll take you up on that then :) Our Windows CI is failing with:

```
  File "unzip.py", line 36, in <module>
  File "unzip.py", line 29, in main
  File "C:\Python27\lib\zipfile.py", line 1053, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1041, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Python27\lib\zipfile.py", line 1096, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: u'C:\\cygwin\\data\\temp\\buck-e827d919-22bd-4490-a98a-39648d155ade\\test\\com\\facebook\\buck\\jvm\\java\\__java_test_java_tmp__\\junit1759102774629287037\\buck-out\\gen\\genjardir\\junit2\\org\\junit\\experimental\\theories\\PotentialAssignment$CouldNotGenerateValueException.class'
```

I tried playing around with the Python code (making sure the directory is created, touching the file first, etc..) but couldn't get it to work.
I'll be on vacation till middle of next week, @Coneko will be able to re-import any changes you've made to the PR, otherwise I'll pick the PR back up after I return.

**Comment by Coneko** [comment]
I'm attempting to fix the AppVeyor build in #761 so hopefully you'll be able to get some more signal soon.

**Comment by mikekap** [comment]
Well this is 😭 worthy:

```
> len('C:\\cygwin\\data\\temp\\buck-e827d919-22bd-4490-a98a-39648d155ade\\test\\com\\facebook\\buck\\jvm\\java\\__java_test_java_tmp__\\junit1759102774629287037\\buck-out\\gen\\genjardir\\junit2\\org\\junit\\experimental\\theories\\PotentialAssignment$CouldNotGenerateValueException.class')
260
```

I'll see if I can prepend `\\?\` and still have everything work...

**Comment by mikekap** [comment]
ping

**Comment by Coneko** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/522582897866656/int_phab) to review.

**Comment by Coneko** [comment]
```
    exec code in run_globals
  File "unzip.py", line 39, in <module>
  File "unzip.py", line 35, in main
AttributeError: ZipFile instance has no attribute '__exit__'
[2016-05-31 02:51:45.736][warn ][tid:5041][com.facebook.buck.event.listener.LoggingBuildListener] BUILD FAILED: //:genjardir failed with exit code 1:
genrule
stderr: Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 320, in execute
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File ".bootstrap/_pex/pex.py", line 223, in patch_pkg_resources
  File ".bootstrap/_pex/pex.py", line 320, in execute
  File ".bootstrap/_pex/pex.py", line 253, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 285, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 363, in _execute
  File ".bootstrap/_pex/pex.py", line 421, in execute_entry
  File ".bootstrap/_pex/pex.py", line 426, in execute_module
  File "/usr/lib64/python2.6/runpy.py", line 140, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "unzip.py", line 39, in <module>
  File "unzip.py", line 35, in main
AttributeError: ZipFile instance has no attribute '__exit__'
[2016-05-31 02:51:45.740][warn ][tid:4770][com.facebook.buck.event.listener.ScubaBuildListener] Still have 1 thread remaining.  Dropping results.
```

**Comment by mikekap** [comment]
Fixed - sorry about that. Turns out pyenv doesn't create a shim for `python2` which is what buck prefers over `python`.

**Comment by facebook-github-bot-8** [comment]
@mikekap updated the pull request.

**Comment by Coneko** [comment]
@facebook-github-bot shipit

**Comment by Coneko** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
