### PR TITLE
Bump d8 to latest 3.6.1 release + buck related changes

### PR DESCRIPTION
**Pull request by raviagarwal7**

### CODE REVIEW

**Comment by v-jizhang** [comment]
@raviagarwal7 
There are some failed CI tests. Please take a look at linux_unit_groovy and macos_unit_grrovy. Thanks

**Comment by raviagarwal7** [comment]
based on https://github.com/facebookexperimental/r8/issues/4
cc: @justinjhendrick

**Comment by v-jizhang** [comment]
@raviagarwal7 
Thank you for you contributions! There are some unrelated test failures(already fixed in other PRs) need to be cleared. Could you rebase and submit this PR again? Thanks.

**Comment by raviagarwal7** [comment]
Thanks @v-jizhang , seems like there are still 2 job failures unrelated to the change.

**Comment by v-jizhang** [comment]
> Thanks @v-jizhang , seems like there are still 2 job failures unrelated to the change.

Looks like related. All failed tests display an error "zipimport.ZipImportError: bad local file header:". Somehow the new jar affects Python zipimport?

**Comment by KapJI** [comment]
More than 6 months without update here, closing for now. Feel free to reopen when you fix these tests.

**Pull request closed without merging**
