### PR TITLE
Fixing FileClassPathRunner to handle directories that contain "@"

### LINKED ISSUE #734: Java tests do not run if the project's path contains "@"
When the project's path contains a directory that contains an "@", Buck fails to run Java tests.

Error:
`Unable to locate junit on the classpath. Please add as a test dependency.`

The root cause is that `FileClassPathRunner` splits the classfile path prematurely -- on the "@" in the project path rather than on the "@" used as a sentinel -- so the classfile cannot be found and is ignored.

For example:
`file:/tmp/buck@2/@/tmp/buck@2/buck-out/gen/test/classpath-file` becomes `2/@/tmp/buck@2/buck-out/gen/test/classpath-file`

One example where this issue comes up in practice is that Jenkins will create workspace directories with "@" for concurrent builds on the same machine (e.g. `workspace@2`).

### PR DESCRIPTION
**Pull request by bocon13**
Summary:
Updated FileClassPathRunner.getClasspathFiles() to scan for "@" only at the
beginning of each section in the path (instead of anywhere in the path). This
allows the project's path include directories that contain "@".

Test Plan: Added new unit test

fixes #734

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @scrawlings to be a potential reviewer.

**Comment by bocon13** [comment]
I have pushed a new commit that simplifies the implementation by using String manipulation instead of Path manipulation because I was worried that the Path-based implementation was causing a test failure in TravisCI (which was not reproducible locally).

**Comment by marcinkosiba** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1539560286348891/int_phab) to review.

**Comment by bocon13** [comment]
Ping... just wanted to see what the status was on this pull request.

Thanks!

**Comment by marcinkosiba** [comment]
> Ping... it's been a few weeks; just wanted to see what the status is on this pull request.
Hey! The diff hit an issue that only happened on internal CI. I'll have another go at debugging+landing this in ~12h

**Comment by bocon13** [comment]
@marcinkosiba Ah, I see. Thanks for the update!

Let me know if I can be of any assistance.

**Pull request closed without merging**
