### PR TITLE
Simplify the method for `getTransitiveClasspath`

### PR DESCRIPTION
**Pull request by shs96c**
Other than one test, we only ever passed in the first argument
as the second argument. *face palm*

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @asp2insp, @yiding and @andrewjcg to be potential reviewers.

**Comment by asp2insp** [comment]
Thanks! I'll take a look. There's a couple of changes landing right now in this area, just as a heads up :)

**Comment by asp2insp** [comment]
Okay, the other work in this area has landed. If you would be willing to rebase, this change looks good by me

**Comment by shs96c** [comment]
Rebased for fun and profit.

**Comment by facebook-github-bot-6** [comment]
@shs96c updated the pull request - [view changes](https://github.com/facebook/buck/pull/885/files/59081688982c80acc9914e623cc73a42d2175eeb..2f29a41f05d6eb8e16b027100e18752e5c20e77b) - [changes since last import](https://github.com/facebook/buck/pull/885/files/59081688982c80acc9914e623cc73a42d2175eeb..2f29a41f05d6eb8e16b027100e18752e5c20e77b)

**Pull request closed without merging**
