### PR TITLE
Update d8 to latest

### PR DESCRIPTION
**Pull request by kageiit**

### CODE REVIEW

**Comment by styurin** [comment]
Could you add information about where you got `kotlinx-metadata-jvm-0.0.2-sources.jar`?

**Comment by kageiit** [comment]
Sure. Let me add a readme

**Comment by kageiit** [comment]
@styurin any update on merging this pr?

**Comment by kageiit** [comment]
@styurin I have updated the pr. kotlin-metadata-jvm is no longer required. Can you please re-import?

**Pull request closed without merging**
