### PR TITLE
Fix AppVeyor build.

### PR DESCRIPTION
**Pull request by Coneko**

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
By analyzing the blame information on this pull request, we identified @mikekap to be a potential reviewer.

**Comment by facebook-github-bot-9** [comment]
@Coneko updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@Coneko updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@Coneko updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@Coneko updated the pull request.

**Comment by mikekap** [comment]
The go tests don't currently work on windows - I think the change that removed them from the blacklist was erroneous: https://github.com/facebook/buck/commit/5fa1d7be1f5d6ee4626af5ab7f3ae8c1e71eb4ce . They might pass with assumption violations if you don't have go installed though.

**Pull request closed without merging**
