### PR TITLE
Opportunity for discussion: expand any zipped java sources in one place

### PR DESCRIPTION
**Pull request by grumpyjames**
Don't merge me, I don't work!

### CODE REVIEW

**Comment by grumpyjames** [comment]
So, this

**Comment by marcinkosiba** [comment]
Thanks for the great writeup! 

I think the Java rules support this as a workaround for the fact that genrules didn't support directories at the time this was added. I don't think it is important to have source .zip support baked in for all jvm-based languages and it's fine for this to stay a java-only feature.

If you wanted to support this later on then we could inject the unzip step based on whether the compiler supports reading directly from .zip files (we could do it by having the compilestepfactory return this information along with the step, for example). We could even pull that into a separate rule (the benefit there is that you could potentially run that 'unzip' rule earlier in the build), though I don't think it's worth it unless we somehow find ourselves flinging a lot of code around in .zip files.

**Comment by grumpyjames** [comment]
Thanks for taking the time to read it - we'll get on with our first go at groovy_library.

**Comment by shs96c** [comment]
I added the `SrcZipAwareFileBundler` to make it easier to work with src zips, which makes option 1 easier to implement. The main thing with the `Jsr199Javac` is that it avoids the need to start a separate compiler process, which reduces the overhead of dealing with things.

**Pull request closed without merging**
