### PR TITLE
Fix support for using .whl files in prebuilt_python_library

### LINKED ISSUE #719: Buck can't use Python Wheels (.whl) as binary_src for prebuilt_python_library because _markerlib isn't vendored
When I build with a whl file as a dependency:

```
prebuilt_python_library(
    name='click',
    binary_src='click-6.6-py2.py3-none-any.whl',
    visibility=['PUBLIC']
)
```

I get the following traceback:

```
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 314, in execute
  File ".bootstrap/_pex/pex.py", line 78, in _activate
  File ".bootstrap/_pex/environment.py", line 132, in activate
  File ".bootstrap/_pex/environment.py", line 184, in _activate
  File ".bootstrap/_pex/environment.py", line 147, in _resolve
  File ".bootstrap/pkg_resources/__init__.py", line 854, in resolve
  File ".bootstrap/pkg_resources/__init__.py", line 2617, in requires
  File ".bootstrap/pkg_resources/__init__.py", line 2818, in _dep_map
  File ".bootstrap/pkg_resources/__init__.py", line 2835, in _compute_dependencies
ImportError: No module named _markerlib
```

In the vendored copy of setuptools we've only kept the pkg_resources resource, but we need to also vendor _markerlib from the 18.5 tree: https://github.com/pypa/setuptools/tree/18.5/_markerlib

This can be fixed by adding _markerlib to our copy of setuptools and then wiring up _markerlib the same as pkg_resources in make_pex.py.

```
copy_package(pex_builder, '_markerlib', prefix=pex_builder.BOOTSTRAP_DIR)
```

### PR DESCRIPTION
**Pull request by borgstrom**
Using wheel files with prebuilt python libraries results in the following traceback:

```
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 314, in execute
  File ".bootstrap/_pex/pex.py", line 78, in _activate
  File ".bootstrap/_pex/environment.py", line 132, in activate
  File ".bootstrap/_pex/environment.py", line 184, in _activate
  File ".bootstrap/_pex/environment.py", line 147, in _resolve
  File ".bootstrap/pkg_resources/__init__.py", line 854, in resolve
  File ".bootstrap/pkg_resources/__init__.py", line 2617, in requires
  File ".bootstrap/pkg_resources/__init__.py", line 2818, in _dep_map
  File ".bootstrap/pkg_resources/__init__.py", line 2835, in _compute_dependencies
ImportError: No module named _markerlib
```

This is because we did not also vendor _markerlib from 18.5 of setuptools.

This commit pulls in _markerlib and adds it to the pex at the same time that pkg_resources is added.

Fixes #719

### CODE REVIEW

**Comment by borgstrom** [comment]
Those check failures don't look to be related to my changes.  In both cases it seems java was killed with signal 9 while running java tests.

**Comment by sdwilsh** [comment]
You'll also need to update https://github.com/facebook/buck/blob/master/third-party/py/setuptools/README.facebook to include the new addition.

**Comment by borgstrom** [comment]
@sdwilsh I did that already.

**Comment by sdwilsh** [comment]
I guess I'm blind today...

**Comment by sdwilsh** [comment]
@facebook-github-bot import

**Comment by borgstrom** [comment]
All good.  Thanks for looking :)

**Comment by sdwilsh** [comment]
I'm waiting on review for this from @andrewjcg (if @mikekap thinks this is good, that's probably fine too)

**Comment by mikekap** [comment]
LGTM. I would suggest adding a test in so this doesn't break again - there's already an egg test there (though you'd want to build a universal wheel since the tests needs to pass on py2.7 & py2.6).

**Comment by sdwilsh** [comment]
Thanks @mikekap!  @borgstrom, let's get that test added and then I can get this in for you :)

**Comment by borgstrom** [comment]
@mikekap @sdwilsh -- python prebuilt test updated.

I commented out the the `copy_package` call to add `_markerlib` and confirmed the test failed:

```
=== Expected exit code 0 but was 1. ===
=== STDERR ===
[-] PARSING BUCK FILES...FINISHED 0.0s [100%]
BUILT //:python_whl (1/2 JOBS)
BUILT //:main_whl (2/2 JOBS)
[-] BUILDING...FINISHED 0.7s [100%]
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 314, in execute
  File ".bootstrap/_pex/pex.py", line 78, in _activate
  File ".bootstrap/_pex/environment.py", line 132, in activate
  File ".bootstrap/_pex/environment.py", line 184, in _activate
  File ".bootstrap/_pex/environment.py", line 147, in _resolve
  File ".bootstrap/pkg_resources/__init__.py", line 854, in resolve
  File ".bootstrap/pkg_resources/__init__.py", line 2617, in requires
  File ".bootstrap/pkg_resources/__init__.py", line 2818, in _dep_map
  File ".bootstrap/pkg_resources/__init__.py", line 2835, in _compute_dependencies
ImportError: No module named _markerlib

=== STDOUT ===


====ERROR LOGS====

[2016-04-25 10:08:09.772][warn ][tid:274][com.facebook.buck.python.PythonBinaryDescription] //:main_egg: parameter `main` is deprecated, please use `main_module` instead.
[2016-04-25 10:08:10.663][warn ][tid:274][com.facebook.buck.python.PythonBinaryDescription] //:main_whl: parameter `main` is deprecated, please use `main_module` instead.

PASS     300ms 19 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonBinaryDescriptionTest
ASSUME   26.1s 36 Passed  12 Skipped   0 Failed   com.facebook.buck.python.PythonBinaryIntegrationTest
PASS    <100ms 15 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonBuckConfigTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonLibraryDescriptionTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonLibraryTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonPackageableComponentsTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonPackagedBinaryTest
PASS      4.3s  1 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonSrcZipIntegrationTest
PASS    <100ms 10 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonTestDescriptionTest
PASS     11.1s  8 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonTestIntegrationTest
PASS     140ms  1 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PythonUtilTest
TESTS FAILED: 1 FAILURE
Failed target: //test/com/facebook/buck/python:python
FAIL com.facebook.buck.python.PrebuiltPythonLibraryIntegrationTest
```

**Comment by borgstrom** [comment]
The prebuilt python library test passed in CI, even though the overall job failed:

    PASS      3.4s  1 Passed   0 Skipped   0 Failed   com.facebook.buck.python.PrebuiltPythonLibraryIntegrationTest

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Comment by sdwilsh** [comment]
Actually, this fails `ant lint`.  You'll have to fix that up for me to be able to merge it.

**Comment by borgstrom** [comment]
Gotcha.  It doesn't like my Python names in the Java sources.  Fix incoming...

**Comment by borgstrom** [comment]
@sdwilsh -- fixed, and `ant lint` passes locally now.

**Comment by sdwilsh** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1093326724063624/int_phab) to review.

**Comment by borgstrom** [comment]
Hey @sdwilsh -- Why is the commit that landed in master attributed to you (7aca2fb) instead of my original commit (ae17e91)?

I looked through a bunch of other commits in master and it seems like any contribution to Buck is being attributed to FB employees rather than the person who actually authored the commit.

I understand that this is applicable under the copyright license grant in the CLA, but I feel it's bad for the community to remove proper attribution.

Thoughts?  Is there somewhere else I should take this discussion?  I tried to bring it up on the FB Developers group, but someone there said I should just respond here.

**Comment by k21** [comment]
That looks like a recent regression in the open-source sync logic. We do rebase all commits to keep a linear history which is why facebook-github-bot shows up as the committer, but the author should be the original contributor. This was the case for pull requests until recently, e.g. 20639e0674d5c1d601386f700e0282770aa7d382, f302d65c8aa67da5a47eff7349424050eb8adbc8 or 2f8f2739bd469aa4eb7ed4b1e018ed1f5635fcf1. Sorry for the inconvenience, I will make sure people maintaining the open-source sync are aware of the issue. Thanks for reporting!

**Comment by sdwilsh** [comment]
Ugh....I'm not trying to take credit for your work; honest!  Looks like 
@k21 raised the issue and it's being looked at.  I'm going to hold of 
merging anything else until it's fixed :/

**Comment by borgstrom** [comment]
Thanks for the replies, @k21 & @sdwilsh. 

I definitely didn't think anyone was doing something nefarious to try and take credit, it's more that I thought this was some internal policy thing at FB.  Glad to hear it's just a regression in a tool.

**Comment by yiding** [comment]
I should have fixed this. Let us know if it crops up again.

**Pull request closed without merging**
